-- Jan Aushadhi Kendras of Saran District SQL Dump (Health Category)
-- Generated on 2026-08-12 22:20:27

INSERT INTO `subcategories` (`id`, `category_id`, `name`, `hindi_name`, `slug`, `keywords`) VALUES
(268, 12, 'Jan Aushadhi Kendra (PMBJK)', 'जन औषधि केंद्र (PMBJK)', 'jan-aushadhi-kendra', 'jan aushadhi kendra, pmbjk, generic medicine store, government medical store, cheap medicine, bharat aushadhi, chapra jan aushadhi, kendra')
ON DUPLICATE KEY UPDATE `category_id`=12, `name`='Jan Aushadhi Kendra (PMBJK)', `hindi_name`='जन औषधि केंद्र (PMBJK)', `keywords`='jan aushadhi kendra, pmbjk, generic medicine store, government medical store, cheap medicine, bharat aushadhi, chapra jan aushadhi, kendra';

-- Listings for Jan Aushadhi Kendras (Total: 58)
INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK07333) - Brajesh Kumar', 'जन औषधि केंद्र (PMBJK07333) - Brajesh Kumar', 'jan-aushadhi-kendra-pmbjk07333', 'Brajesh Kumar', '18001808080', 'https://janaushadhi.gov.in/', 'Rajeshwari Bhawan Shekhpura Dih Dharhara Kala, Chhapra', '841218', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK07333) in Saran District. Managed by Brajesh Kumar. Address: Rajeshwari Bhawan Shekhpura Dih Dharhara Kala, Chhapra, Pincode: 841218. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK07333) - Brajesh Kumar', `hindi_title`='जन औषधि केंद्र (PMBJK07333) - Brajesh Kumar', `address`='Rajeshwari Bhawan Shekhpura Dih Dharhara Kala, Chhapra', `pincode`='841218';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 10, 'Jan Aushadhi Kendra (PMBJK09790) - Priyanka Mishra', 'जन औषधि केंद्र (PMBJK09790) - Priyanka Mishra', 'jan-aushadhi-kendra-pmbjk09790', 'Priyanka Mishra', '18001808080', 'https://janaushadhi.gov.in/', 'Hansrajpur Tola Goapli, Block Road Near P.H.C', '841208', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK09790) in Saran District. Managed by Priyanka Mishra. Address: Hansrajpur Tola Goapli, Block Road Near P.H.C, Pincode: 841208. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK09790) - Priyanka Mishra', `hindi_title`='जन औषधि केंद्र (PMBJK09790) - Priyanka Mishra', `address`='Hansrajpur Tola Goapli, Block Road Near P.H.C', `pincode`='841208';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 11, 'Jan Aushadhi Kendra (PMBJK09878) - Shobha Singh', 'जन औषधि केंद्र (PMBJK09878) - Shobha Singh', 'jan-aushadhi-kendra-pmbjk09878', 'Shobha Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Kondh,Bhagwanpur Bazar', '841424', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK09878) in Saran District. Managed by Shobha Singh. Address: Kondh,Bhagwanpur Bazar, Pincode: 841424. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK09878) - Shobha Singh', `hindi_title`='जन औषधि केंद्र (PMBJK09878) - Shobha Singh', `address`='Kondh,Bhagwanpur Bazar', `pincode`='841424';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 6, 'Jan Aushadhi Kendra (PMBJK10256) - Manoj Kumar Dubey', 'जन औषधि केंद्र (PMBJK10256) - Manoj Kumar Dubey', 'jan-aushadhi-kendra-pmbjk10256', 'Manoj Kumar Dubey', '18001808080', 'https://janaushadhi.gov.in/', 'Bheldi Bazar, Parsa', '841402', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK10256) in Saran District. Managed by Manoj Kumar Dubey. Address: Bheldi Bazar, Parsa, Pincode: 841402. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK10256) - Manoj Kumar Dubey', `hindi_title`='जन औषधि केंद्र (PMBJK10256) - Manoj Kumar Dubey', `address`='Bheldi Bazar, Parsa', `pincode`='841402';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 13, 'Jan Aushadhi Kendra (PMBJK10928) - Meera Devi', 'जन औषधि केंद्र (PMBJK10928) - Meera Devi', 'jan-aushadhi-kendra-pmbjk10928', 'Meera Devi', '18001808080', 'https://janaushadhi.gov.in/', 'Lahladpur, Janta Bazar', '840126', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK10928) in Saran District. Managed by Meera Devi. Address: Lahladpur, Janta Bazar, Pincode: 840126. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK10928) - Meera Devi', `hindi_title`='जन औषधि केंद्र (PMBJK10928) - Meera Devi', `address`='Lahladpur, Janta Bazar', `pincode`='840126';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 14, 'Jan Aushadhi Kendra (PMBJK11221) - Yogendra Sah', 'जन औषधि केंद्र (PMBJK11221) - Yogendra Sah', 'jan-aushadhi-kendra-pmbjk11221', 'Yogendra Sah', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Bipin Kumar Sharma, Rasulpur Chainpur Road', '841204', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK11221) in Saran District. Managed by Yogendra Sah. Address: H/O Bipin Kumar Sharma, Rasulpur Chainpur Road, Pincode: 841204. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK11221) - Yogendra Sah', `hindi_title`='जन औषधि केंद्र (PMBJK11221) - Yogendra Sah', `address`='H/O Bipin Kumar Sharma, Rasulpur Chainpur Road', `pincode`='841204';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 17, 'Jan Aushadhi Kendra (PMBJK11284) - Aditi Bhardwaz', 'जन औषधि केंद्र (PMBJK11284) - Aditi Bhardwaz', 'jan-aushadhi-kendra-pmbjk11284', 'Aditi Bhardwaz', '18001808080', 'https://janaushadhi.gov.in/', '1st Floor, Sudish Tiwary Market Bazar', '841412', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK11284) in Saran District. Managed by Aditi Bhardwaz. Address: 1st Floor, Sudish Tiwary Market Bazar, Pincode: 841412. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK11284) - Aditi Bhardwaz', `hindi_title`='जन औषधि केंद्र (PMBJK11284) - Aditi Bhardwaz', `address`='1st Floor, Sudish Tiwary Market Bazar', `pincode`='841412';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK11424) - Anjali Kumari', 'जन औषधि केंद्र (PMBJK11424) - Anjali Kumari', 'jan-aushadhi-kendra-pmbjk11424', 'Anjali Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Bolbam Market, Vill+PO-Lawan Kala, Tedhi Ghat Bazar', '841403', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK11424) in Saran District. Managed by Anjali Kumari. Address: Bolbam Market, Vill+PO-Lawan Kala, Tedhi Ghat Bazar, Pincode: 841403. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK11424) - Anjali Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK11424) - Anjali Kumari', `address`='Bolbam Market, Vill+PO-Lawan Kala, Tedhi Ghat Bazar', `pincode`='841403';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK11850) - Sangita Kumari', 'जन औषधि केंद्र (PMBJK11850) - Sangita Kumari', 'jan-aushadhi-kendra-pmbjk11850', 'Sangita Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Shri Chhathi Lal Rai, Ramrajya Chowk, Near Gandhi Karyalay, Dahiyawan Chowk', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK11850) in Saran District. Managed by Sangita Kumari. Address: H/O Shri Chhathi Lal Rai, Ramrajya Chowk, Near Gandhi Karyalay, Dahiyawan Chowk, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK11850) - Sangita Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK11850) - Sangita Kumari', `address`='H/O Shri Chhathi Lal Rai, Ramrajya Chowk, Near Gandhi Karyalay, Dahiyawan Chowk', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 3, 'Jan Aushadhi Kendra (PMBJK12465) - Chhote Lal Gupta', 'जन औषधि केंद्र (PMBJK12465) - Chhote Lal Gupta', 'jan-aushadhi-kendra-pmbjk12465', 'Chhote Lal Gupta', '18001808080', 'https://janaushadhi.gov.in/', 'Vill-Rasulpur, Nayagaon, Po+Ps- Nayagaon', '841217', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK12465) in Saran District. Managed by Chhote Lal Gupta. Address: Vill-Rasulpur, Nayagaon, Po+Ps- Nayagaon, Pincode: 841217. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK12465) - Chhote Lal Gupta', `hindi_title`='जन औषधि केंद्र (PMBJK12465) - Chhote Lal Gupta', `address`='Vill-Rasulpur, Nayagaon, Po+Ps- Nayagaon', `pincode`='841217';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK13674) - Rani Kumari', 'जन औषधि केंद्र (PMBJK13674) - Rani Kumari', 'jan-aushadhi-kendra-pmbjk13674', 'Rani Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Champa Devi Dahiyawan Tola, Joginia Kothi', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK13674) in Saran District. Managed by Rani Kumari. Address: H/O Champa Devi Dahiyawan Tola, Joginia Kothi, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK13674) - Rani Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK13674) - Rani Kumari', `address`='H/O Champa Devi Dahiyawan Tola, Joginia Kothi', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 11, 'Jan Aushadhi Kendra (PMBJK14406) - Muskan Singh', 'जन औषधि केंद्र (PMBJK14406) - Muskan Singh', 'jan-aushadhi-kendra-pmbjk14406', 'Muskan Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Ground Floor, nandkishor Market, Taraiya Bazaar', '841424', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK14406) in Saran District. Managed by Muskan Singh. Address: Ground Floor, nandkishor Market, Taraiya Bazaar, Pincode: 841424. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK14406) - Muskan Singh', `hindi_title`='जन औषधि केंद्र (PMBJK14406) - Muskan Singh', `address`='Ground Floor, nandkishor Market, Taraiya Bazaar', `pincode`='841424';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK14983) - Ankita Kumari', 'जन औषधि केंद्र (PMBJK14983) - Ankita Kumari', 'jan-aushadhi-kendra-pmbjk14983', 'Ankita Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'H/O-Pramod Kumar Kathari Bagh Road, Near-Maula Masjid, Chapra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK14983) in Saran District. Managed by Ankita Kumari. Address: H/O-Pramod Kumar Kathari Bagh Road, Near-Maula Masjid, Chapra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK14983) - Ankita Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK14983) - Ankita Kumari', `address`='H/O-Pramod Kumar Kathari Bagh Road, Near-Maula Masjid, Chapra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 20, 'Jan Aushadhi Kendra (PMBJK15532) - Sugandhi Devi', 'जन औषधि केंद्र (PMBJK15532) - Sugandhi Devi', 'jan-aushadhi-kendra-pmbjk15532', 'Sugandhi Devi', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Rajendra Prasad Singh Mashrak Road, Fardahiya, Dumarsan Bazar', '841410', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK15532) in Saran District. Managed by Sugandhi Devi. Address: H/O Rajendra Prasad Singh Mashrak Road, Fardahiya, Dumarsan Bazar, Pincode: 841410. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK15532) - Sugandhi Devi', `hindi_title`='जन औषधि केंद्र (PMBJK15532) - Sugandhi Devi', `address`='H/O Rajendra Prasad Singh Mashrak Road, Fardahiya, Dumarsan Bazar', `pincode`='841410';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK16084) - Shashi Prabha', 'जन औषधि केंद्र (PMBJK16084) - Shashi Prabha', 'jan-aushadhi-kendra-pmbjk16084', 'Shashi Prabha', '18001808080', 'https://janaushadhi.gov.in/', 'Pioneer Complex , Main Road, Bhagwan Bazar, Chapra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK16084) in Saran District. Managed by Shashi Prabha. Address: Pioneer Complex , Main Road, Bhagwan Bazar, Chapra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK16084) - Shashi Prabha', `hindi_title`='जन औषधि केंद्र (PMBJK16084) - Shashi Prabha', `address`='Pioneer Complex , Main Road, Bhagwan Bazar, Chapra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK16739) - Ibrar Alam', 'जन औषधि केंद्र (PMBJK16739) - Ibrar Alam', 'jan-aushadhi-kendra-pmbjk16739', 'Ibrar Alam', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Abdul Faruque Ansari, Bishunpura', '841411', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK16739) in Saran District. Managed by Ibrar Alam. Address: H/O Abdul Faruque Ansari, Bishunpura, Pincode: 841411. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK16739) - Ibrar Alam', `hindi_title`='जन औषधि केंद्र (PMBJK16739) - Ibrar Alam', `address`='H/O Abdul Faruque Ansari, Bishunpura', `pincode`='841411';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 19, 'Jan Aushadhi Kendra (PMBJK16932) - Priti Kumari', 'जन औषधि केंद्र (PMBJK16932) - Priti Kumari', 'jan-aushadhi-kendra-pmbjk16932', 'Priti Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'H/O- Punam Devi, Vill', '841417', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK16932) in Saran District. Managed by Priti Kumari. Address: H/O- Punam Devi, Vill, Pincode: 841417. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK16932) - Priti Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK16932) - Priti Kumari', `address`='H/O- Punam Devi, Vill', `pincode`='841417';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK17299) - Manoj Kumar', 'जन औषधि केंद्र (PMBJK17299) - Manoj Kumar', 'jan-aushadhi-kendra-pmbjk17299', 'Manoj Kumar', '18001808080', 'https://janaushadhi.gov.in/', 'H/O-Suganti Devi, Ward No-12, Sadha', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK17299) in Saran District. Managed by Manoj Kumar. Address: H/O-Suganti Devi, Ward No-12, Sadha, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK17299) - Manoj Kumar', `hindi_title`='जन औषधि केंद्र (PMBJK17299) - Manoj Kumar', `address`='H/O-Suganti Devi, Ward No-12, Sadha', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 5, 'Jan Aushadhi Kendra (PMBJK17352) - Mausam', 'जन औषधि केंद्र (PMBJK17352) - Mausam', 'jan-aushadhi-kendra-pmbjk17352', 'Mausam', '18001808080', 'https://janaushadhi.gov.in/', 'H/O- Kundan Kumar Baitha, Garkha Bajar Chowk', '841311', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK17352) in Saran District. Managed by Mausam. Address: H/O- Kundan Kumar Baitha, Garkha Bajar Chowk, Pincode: 841311. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK17352) - Mausam', `hindi_title`='जन औषधि केंद्र (PMBJK17352) - Mausam', `address`='H/O- Kundan Kumar Baitha, Garkha Bajar Chowk', `pincode`='841311';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 3, 'Jan Aushadhi Kendra (PMBJK17356) - Madhu Singh', 'जन औषधि केंद्र (PMBJK17356) - Madhu Singh', 'jan-aushadhi-kendra-pmbjk17356', 'Madhu Singh', '18001808080', 'https://janaushadhi.gov.in/', 'H/o Dina Nath Singh, Dudhalla Gacchi', '841101', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK17356) in Saran District. Managed by Madhu Singh. Address: H/o Dina Nath Singh, Dudhalla Gacchi, Pincode: 841101. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK17356) - Madhu Singh', `hindi_title`='जन औषधि केंद्र (PMBJK17356) - Madhu Singh', `address`='H/o Dina Nath Singh, Dudhalla Gacchi', `pincode`='841101';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 14, 'Jan Aushadhi Kendra (PMBJK17483) - Ragani Devi', 'जन औषधि केंद्र (PMBJK17483) - Ragani Devi', 'jan-aushadhi-kendra-pmbjk17483', 'Ragani Devi', '18001808080', 'https://janaushadhi.gov.in/', 'H/O-Ram Naresh Gupta Kopa Bazar, Near-Durga Mandir', '841214', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK17483) in Saran District. Managed by Ragani Devi. Address: H/O-Ram Naresh Gupta Kopa Bazar, Near-Durga Mandir, Pincode: 841214. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK17483) - Ragani Devi', `hindi_title`='जन औषधि केंद्र (PMBJK17483) - Ragani Devi', `address`='H/O-Ram Naresh Gupta Kopa Bazar, Near-Durga Mandir', `pincode`='841214';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK17651) - Swati Yadav', 'जन औषधि केंद्र (PMBJK17651) - Swati Yadav', 'jan-aushadhi-kendra-pmbjk17651', 'Swati Yadav', '18001808080', 'https://janaushadhi.gov.in/', 'H/O-MD. Naushad Ali Chanchaura Bajar', '841414', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK17651) in Saran District. Managed by Swati Yadav. Address: H/O-MD. Naushad Ali Chanchaura Bajar, Pincode: 841414. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK17651) - Swati Yadav', `hindi_title`='जन औषधि केंद्र (PMBJK17651) - Swati Yadav', `address`='H/O-MD. Naushad Ali Chanchaura Bajar', `pincode`='841414';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK18578) - Md. Zunaid Akhatar', 'जन औषधि केंद्र (PMBJK18578) - Md. Zunaid Akhatar', 'jan-aushadhi-kendra-pmbjk18578', 'Md. Zunaid Akhatar', '18001808080', 'https://janaushadhi.gov.in/', 'H/O- MD Naimulah Vill- Karah Niyamat Tola', '841403', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK18578) in Saran District. Managed by Md. Zunaid Akhatar. Address: H/O- MD Naimulah Vill- Karah Niyamat Tola, Pincode: 841403. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK18578) - Md. Zunaid Akhatar', `hindi_title`='जन औषधि केंद्र (PMBJK18578) - Md. Zunaid Akhatar', `address`='H/O- MD Naimulah Vill- Karah Niyamat Tola', `pincode`='841403';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 18, 'Jan Aushadhi Kendra (PMBJK18585) - Punam Devi', 'जन औषधि केंद्र (PMBJK18585) - Punam Devi', 'jan-aushadhi-kendra-pmbjk18585', 'Punam Devi', '18001808080', 'https://janaushadhi.gov.in/', 'Vill- Kadipur, PO-Nagra, PS- Khaira', '841442', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK18585) in Saran District. Managed by Punam Devi. Address: Vill- Kadipur, PO-Nagra, PS- Khaira, Pincode: 841442. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK18585) - Punam Devi', `hindi_title`='जन औषधि केंद्र (PMBJK18585) - Punam Devi', `address`='Vill- Kadipur, PO-Nagra, PS- Khaira', `pincode`='841442';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK19558) - Priyata Singh', 'जन औषधि केंद्र (PMBJK19558) - Priyata Singh', 'jan-aushadhi-kendra-pmbjk19558', 'Priyata Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Kaushal Complex, Bara Telpa, Nai Basti, Chapra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19558) in Saran District. Managed by Priyata Singh. Address: Kaushal Complex, Bara Telpa, Nai Basti, Chapra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19558) - Priyata Singh', `hindi_title`='जन औषधि केंद्र (PMBJK19558) - Priyata Singh', `address`='Kaushal Complex, Bara Telpa, Nai Basti, Chapra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 10, 'Jan Aushadhi Kendra (PMBJK19560) - Priyanka Kumari Singh', 'जन औषधि केंद्र (PMBJK19560) - Priyanka Kumari Singh', 'jan-aushadhi-kendra-pmbjk19560', 'Priyanka Kumari Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Yamuna Singh College, Ekma Saran', '841208', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19560) in Saran District. Managed by Priyanka Kumari Singh. Address: Yamuna Singh College, Ekma Saran, Pincode: 841208. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19560) - Priyanka Kumari Singh', `hindi_title`='जन औषधि केंद्र (PMBJK19560) - Priyanka Kumari Singh', `address`='Yamuna Singh College, Ekma Saran', `pincode`='841208';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK19582) - Kamna Singh', 'जन औषधि केंद्र (PMBJK19582) - Kamna Singh', 'jan-aushadhi-kendra-pmbjk19582', 'Kamna Singh', '18001808080', 'https://janaushadhi.gov.in/', '105, Gandhi Chowk, Garkha Road, Chapra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19582) in Saran District. Managed by Kamna Singh. Address: 105, Gandhi Chowk, Garkha Road, Chapra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19582) - Kamna Singh', `hindi_title`='जन औषधि केंद्र (PMBJK19582) - Kamna Singh', `address`='105, Gandhi Chowk, Garkha Road, Chapra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 19, 'Jan Aushadhi Kendra (PMBJK19622) - Deepakkumar Narendra Singh', 'जन औषधि केंद्र (PMBJK19622) - Deepakkumar Narendra Singh', 'jan-aushadhi-kendra-pmbjk19622', 'Deepakkumar Narendra Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Dumduma Mashrak, Saran', '841417', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19622) in Saran District. Managed by Deepakkumar Narendra Singh. Address: Dumduma Mashrak, Saran, Pincode: 841417. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19622) - Deepakkumar Narendra Singh', `hindi_title`='जन औषधि केंद्र (PMBJK19622) - Deepakkumar Narendra Singh', `address`='Dumduma Mashrak, Saran', `pincode`='841417';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 5, 'Jan Aushadhi Kendra (PMBJK19689) - Shyambabu Singh', 'जन औषधि केंद्र (PMBJK19689) - Shyambabu Singh', 'jan-aushadhi-kendra-pmbjk19689', 'Shyambabu Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Garkha Chintamanganj Bazar, Saran', '841311', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19689) in Saran District. Managed by Shyambabu Singh. Address: Garkha Chintamanganj Bazar, Saran, Pincode: 841311. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19689) - Shyambabu Singh', `hindi_title`='जन औषधि केंद्र (PMBJK19689) - Shyambabu Singh', `address`='Garkha Chintamanganj Bazar, Saran', `pincode`='841311';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 16, 'Jan Aushadhi Kendra (PMBJK19785) - Amrita Devi', 'जन औषधि केंद्र (PMBJK19785) - Amrita Devi', 'jan-aushadhi-kendra-pmbjk19785', 'Amrita Devi', '18001808080', 'https://janaushadhi.gov.in/', 'One Guruji Market Station Road', '841221', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19785) in Saran District. Managed by Amrita Devi. Address: One Guruji Market Station Road, Pincode: 841221. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19785) - Amrita Devi', `hindi_title`='जन औषधि केंद्र (PMBJK19785) - Amrita Devi', `address`='One Guruji Market Station Road', `pincode`='841221';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK19815) - Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor', 'जन औषधि केंद्र (PMBJK19815) - Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor', 'jan-aushadhi-kendra-pmbjk19815', 'Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor', '18001808080', 'https://janaushadhi.gov.in/', 'Circulating Area Towards Platform No.1, In Chhapra Jn Railway Station of Varanasi Division', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19815) in Saran District. Managed by Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor. Address: Circulating Area Towards Platform No.1, In Chhapra Jn Railway Station of Varanasi Division, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19815) - Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor', `hindi_title`='जन औषधि केंद्र (PMBJK19815) - Janta Enterprises (Mr. Shakeeb Ahmed As Proprietor', `address`='Circulating Area Towards Platform No.1, In Chhapra Jn Railway Station of Varanasi Division', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK19932) - Suman Kumari', 'जन औषधि केंद्र (PMBJK19932) - Suman Kumari', 'jan-aushadhi-kendra-pmbjk19932', 'Suman Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Mahavir Rai, Gudri Bazaar, P O Sahebganj', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK19932) in Saran District. Managed by Suman Kumari. Address: H/O Mahavir Rai, Gudri Bazaar, P O Sahebganj, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK19932) - Suman Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK19932) - Suman Kumari', `address`='H/O Mahavir Rai, Gudri Bazaar, P O Sahebganj', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK20147) - Rukhsar Parween', 'जन औषधि केंद्र (PMBJK20147) - Rukhsar Parween', 'jan-aushadhi-kendra-pmbjk20147', 'Rukhsar Parween', '18001808080', 'https://janaushadhi.gov.in/', 'Near Govt. Hospital PHC', '841403', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20147) in Saran District. Managed by Rukhsar Parween. Address: Near Govt. Hospital PHC, Pincode: 841403. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20147) - Rukhsar Parween', `hindi_title`='जन औषधि केंद्र (PMBJK20147) - Rukhsar Parween', `address`='Near Govt. Hospital PHC', `pincode`='841403';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 6, 'Jan Aushadhi Kendra (PMBJK20253) - Alka Roy', 'जन औषधि केंद्र (PMBJK20253) - Alka Roy', 'jan-aushadhi-kendra-pmbjk20253', 'Alka Roy', '18001808080', 'https://janaushadhi.gov.in/', 'Opposite Jal Sansadhan Office, Sankardih, Po/Ps- Parsa', '841219', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20253) in Saran District. Managed by Alka Roy. Address: Opposite Jal Sansadhan Office, Sankardih, Po/Ps- Parsa, Pincode: 841219. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20253) - Alka Roy', `hindi_title`='जन औषधि केंद्र (PMBJK20253) - Alka Roy', `address`='Opposite Jal Sansadhan Office, Sankardih, Po/Ps- Parsa', `pincode`='841219';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK20380) - Praveena Singh', 'जन औषधि केंद्र (PMBJK20380) - Praveena Singh', 'jan-aushadhi-kendra-pmbjk20380', 'Praveena Singh', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Pashupatinath Singh, Newaji Tola, Chapra Sadar', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20380) in Saran District. Managed by Praveena Singh. Address: H/O Pashupatinath Singh, Newaji Tola, Chapra Sadar, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20380) - Praveena Singh', `hindi_title`='जन औषधि केंद्र (PMBJK20380) - Praveena Singh', `address`='H/O Pashupatinath Singh, Newaji Tola, Chapra Sadar', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK20424) - Supriya Rana', 'जन औषधि केंद्र (PMBJK20424) - Supriya Rana', 'jan-aushadhi-kendra-pmbjk20424', 'Supriya Rana', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Ums Singh, Ward-3, Near Biggest Hanuman Ji Statue, Prabhunath Nagar', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20424) in Saran District. Managed by Supriya Rana. Address: H/O Ums Singh, Ward-3, Near Biggest Hanuman Ji Statue, Prabhunath Nagar, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20424) - Supriya Rana', `hindi_title`='जन औषधि केंद्र (PMBJK20424) - Supriya Rana', `address`='H/O Ums Singh, Ward-3, Near Biggest Hanuman Ji Statue, Prabhunath Nagar', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 14, 'Jan Aushadhi Kendra (PMBJK20426) - Sanjit Kumar', 'जन औषधि केंद्र (PMBJK20426) - Sanjit Kumar', 'jan-aushadhi-kendra-pmbjk20426', 'Sanjit Kumar', '18001808080', 'https://janaushadhi.gov.in/', 'Daudpur Bazar', '841205', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20426) in Saran District. Managed by Sanjit Kumar. Address: Daudpur Bazar, Pincode: 841205. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20426) - Sanjit Kumar', `hindi_title`='जन औषधि केंद्र (PMBJK20426) - Sanjit Kumar', `address`='Daudpur Bazar', `pincode`='841205';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 19, 'Jan Aushadhi Kendra (PMBJK20555) - Laxmi Singh', 'जन औषधि केंद्र (PMBJK20555) - Laxmi Singh', 'jan-aushadhi-kendra-pmbjk20555', 'Laxmi Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Bahrauli, Mashrakh Maimaliya Road', '841417', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20555) in Saran District. Managed by Laxmi Singh. Address: Bahrauli, Mashrakh Maimaliya Road, Pincode: 841417. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20555) - Laxmi Singh', `hindi_title`='जन औषधि केंद्र (PMBJK20555) - Laxmi Singh', `address`='Bahrauli, Mashrakh Maimaliya Road', `pincode`='841417';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK20667) - Neelu Kumari', 'जन औषधि केंद्र (PMBJK20667) - Neelu Kumari', 'jan-aushadhi-kendra-pmbjk20667', 'Neelu Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Khakhi Mathiya Bazar, Baniyapur', '841403', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20667) in Saran District. Managed by Neelu Kumari. Address: Khakhi Mathiya Bazar, Baniyapur, Pincode: 841403. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20667) - Neelu Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK20667) - Neelu Kumari', `address`='Khakhi Mathiya Bazar, Baniyapur', `pincode`='841403';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK20696) - Mani Pandey', 'जन औषधि केंद्र (PMBJK20696) - Mani Pandey', 'jan-aushadhi-kendra-pmbjk20696', 'Mani Pandey', '18001808080', 'https://janaushadhi.gov.in/', 'Prabhunath Nagar, Dahiyawa Tola', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20696) in Saran District. Managed by Mani Pandey. Address: Prabhunath Nagar, Dahiyawa Tola, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20696) - Mani Pandey', `hindi_title`='जन औषधि केंद्र (PMBJK20696) - Mani Pandey', `address`='Prabhunath Nagar, Dahiyawa Tola', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 20, 'Jan Aushadhi Kendra (PMBJK20713) - Kumari Suruchi', 'जन औषधि केंद्र (PMBJK20713) - Kumari Suruchi', 'jan-aushadhi-kendra-pmbjk20713', 'Kumari Suruchi', '18001808080', 'https://janaushadhi.gov.in/', 'H/O Udho Singh, Satjora Bazaar, Main Road, Satjora Lakhanpur, Panapur', '841410', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20713) in Saran District. Managed by Kumari Suruchi. Address: H/O Udho Singh, Satjora Bazaar, Main Road, Satjora Lakhanpur, Panapur, Pincode: 841410. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20713) - Kumari Suruchi', `hindi_title`='जन औषधि केंद्र (PMBJK20713) - Kumari Suruchi', `address`='H/O Udho Singh, Satjora Bazaar, Main Road, Satjora Lakhanpur, Panapur', `pincode`='841410';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 7, 'Jan Aushadhi Kendra (PMBJK20784) - Munni Gupta', 'जन औषधि केंद्र (PMBJK20784) - Munni Gupta', 'jan-aushadhi-kendra-pmbjk20784', 'Munni Gupta', '18001808080', 'https://janaushadhi.gov.in/', 'Dighwara Bazzar, Dighwara', '841207', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20784) in Saran District. Managed by Munni Gupta. Address: Dighwara Bazzar, Dighwara, Pincode: 841207. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20784) - Munni Gupta', `hindi_title`='जन औषधि केंद्र (PMBJK20784) - Munni Gupta', `address`='Dighwara Bazzar, Dighwara', `pincode`='841207';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 10, 'Jan Aushadhi Kendra (PMBJK20898) - Ganesh Mahato (Manager)', 'जन औषधि केंद्र (PMBJK20898) - Ganesh Mahato (Manager)', 'jan-aushadhi-kendra-pmbjk20898', 'Ganesh Mahato (Manager)', '18001808080', 'https://janaushadhi.gov.in/', 'Villagen Parsa Bazaar Block Ekma Ps Ekma', '841220', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20898) in Saran District. Managed by Ganesh Mahato (Manager). Address: Villagen Parsa Bazaar Block Ekma Ps Ekma, Pincode: 841220. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20898) - Ganesh Mahato (Manager)', `hindi_title`='जन औषधि केंद्र (PMBJK20898) - Ganesh Mahato (Manager)', `address`='Villagen Parsa Bazaar Block Ekma Ps Ekma', `pincode`='841220';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 3, 'Jan Aushadhi Kendra (PMBJK20908) - Ankita Kumari', 'जन औषधि केंद्र (PMBJK20908) - Ankita Kumari', 'jan-aushadhi-kendra-pmbjk20908', 'Ankita Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Sitabganj Bazar, Nayagoon', '841101', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK20908) in Saran District. Managed by Ankita Kumari. Address: Sitabganj Bazar, Nayagoon, Pincode: 841101. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK20908) - Ankita Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK20908) - Ankita Kumari', `address`='Sitabganj Bazar, Nayagoon', `pincode`='841101';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK21197) - Asif Aquebal', 'जन औषधि केंद्र (PMBJK21197) - Asif Aquebal', 'jan-aushadhi-kendra-pmbjk21197', 'Asif Aquebal', '18001808080', 'https://janaushadhi.gov.in/', 'Vill/Po- Khodaibagh, Ps Khaira', '841415', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21197) in Saran District. Managed by Asif Aquebal. Address: Vill/Po- Khodaibagh, Ps Khaira, Pincode: 841415. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21197) - Asif Aquebal', `hindi_title`='जन औषधि केंद्र (PMBJK21197) - Asif Aquebal', `address`='Vill/Po- Khodaibagh, Ps Khaira', `pincode`='841415';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 2, 'Jan Aushadhi Kendra (PMBJK21360) - Rupa Kumari', 'जन औषधि केंद्र (PMBJK21360) - Rupa Kumari', 'jan-aushadhi-kendra-pmbjk21360', 'Rupa Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Marhaura Dhenuki, Near Petrol Pump', '841418', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21360) in Saran District. Managed by Rupa Kumari. Address: Marhaura Dhenuki, Near Petrol Pump, Pincode: 841418. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21360) - Rupa Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21360) - Rupa Kumari', `address`='Marhaura Dhenuki, Near Petrol Pump', `pincode`='841418';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 10, 'Jan Aushadhi Kendra (PMBJK21560) - Khushboo Kumari', 'जन औषधि केंद्र (PMBJK21560) - Khushboo Kumari', 'jan-aushadhi-kendra-pmbjk21560', 'Khushboo Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Umashankar More Parsagarh, Near Central Bank Of India, Parsagarh Bazar', '841220', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21560) in Saran District. Managed by Khushboo Kumari. Address: Umashankar More Parsagarh, Near Central Bank Of India, Parsagarh Bazar, Pincode: 841220. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21560) - Khushboo Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21560) - Khushboo Kumari', `address`='Umashankar More Parsagarh, Near Central Bank Of India, Parsagarh Bazar', `pincode`='841220';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK21688) - Priyanka Kumari', 'जन औषधि केंद्र (PMBJK21688) - Priyanka Kumari', 'jan-aushadhi-kendra-pmbjk21688', 'Priyanka Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Mauna Chowk Chapra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21688) in Saran District. Managed by Priyanka Kumari. Address: Mauna Chowk Chapra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21688) - Priyanka Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21688) - Priyanka Kumari', `address`='Mauna Chowk Chapra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 1, 'Jan Aushadhi Kendra (PMBJK21784) - Kiran Kumari', 'जन औषधि केंद्र (PMBJK21784) - Kiran Kumari', 'jan-aushadhi-kendra-pmbjk21784', 'Kiran Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Near Jhunjhun Palace, Sadha Bus Stand Sadar Chappra', '841301', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21784) in Saran District. Managed by Kiran Kumari. Address: Near Jhunjhun Palace, Sadha Bus Stand Sadar Chappra, Pincode: 841301. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21784) - Kiran Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21784) - Kiran Kumari', `address`='Near Jhunjhun Palace, Sadha Bus Stand Sadar Chappra', `pincode`='841301';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 14, 'Jan Aushadhi Kendra (PMBJK21935) - Raginee Kumari', 'जन औषधि केंद्र (PMBJK21935) - Raginee Kumari', 'jan-aushadhi-kendra-pmbjk21935', 'Raginee Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Mura, Rasulpur', '841419', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21935) in Saran District. Managed by Raginee Kumari. Address: Mura, Rasulpur, Pincode: 841419. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21935) - Raginee Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21935) - Raginee Kumari', `address`='Mura, Rasulpur', `pincode`='841419';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 3, 'Jan Aushadhi Kendra (PMBJK21944) - Pratima Kumari', 'जन औषधि केंद्र (PMBJK21944) - Pratima Kumari', 'jan-aushadhi-kendra-pmbjk21944', 'Pratima Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Vill Kalyanpur Po Baijalpur, Ps- Sonpur', '841101', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK21944) in Saran District. Managed by Pratima Kumari. Address: Vill Kalyanpur Po Baijalpur, Ps- Sonpur, Pincode: 841101. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK21944) - Pratima Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK21944) - Pratima Kumari', `address`='Vill Kalyanpur Po Baijalpur, Ps- Sonpur', `pincode`='841101';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 18, 'Jan Aushadhi Kendra (PMBJK22042) - Sakila Khatun', 'जन औषधि केंद्र (PMBJK22042) - Sakila Khatun', 'jan-aushadhi-kendra-pmbjk22042', 'Sakila Khatun', '18001808080', 'https://janaushadhi.gov.in/', 'Siswa Saran', '841442', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK22042) in Saran District. Managed by Sakila Khatun. Address: Siswa Saran, Pincode: 841442. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK22042) - Sakila Khatun', `hindi_title`='जन औषधि केंद्र (PMBJK22042) - Sakila Khatun', `address`='Siswa Saran', `pincode`='841442';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 18, 'Jan Aushadhi Kendra (PMBJK22626) - Nitu Kumari', 'जन औषधि केंद्र (PMBJK22626) - Nitu Kumari', 'jan-aushadhi-kendra-pmbjk22626', 'Nitu Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Vill Hathisar, Po/Ps Gaura', '841443', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK22626) in Saran District. Managed by Nitu Kumari. Address: Vill Hathisar, Po/Ps Gaura, Pincode: 841443. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK22626) - Nitu Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK22626) - Nitu Kumari', `address`='Vill Hathisar, Po/Ps Gaura', `pincode`='841443';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 20, 'Jan Aushadhi Kendra (PMBJK22768) - Sulekha Kumari', 'जन औषधि केंद्र (PMBJK22768) - Sulekha Kumari', 'jan-aushadhi-kendra-pmbjk22768', 'Sulekha Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Mashrakh Road, Dumarsan', '841410', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK22768) in Saran District. Managed by Sulekha Kumari. Address: Mashrakh Road, Dumarsan, Pincode: 841410. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK22768) - Sulekha Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK22768) - Sulekha Kumari', `address`='Mashrakh Road, Dumarsan', `pincode`='841410';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 14, 'Jan Aushadhi Kendra (PMBJK22984) - Manish Kumar Singh', 'जन औषधि केंद्र (PMBJK22984) - Manish Kumar Singh', 'jan-aushadhi-kendra-pmbjk22984', 'Manish Kumar Singh', '18001808080', 'https://janaushadhi.gov.in/', 'Manjhi Uttar Tola', '841313', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK22984) in Saran District. Managed by Manish Kumar Singh. Address: Manjhi Uttar Tola, Pincode: 841313. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK22984) - Manish Kumar Singh', `hindi_title`='जन औषधि केंद्र (PMBJK22984) - Manish Kumar Singh', `address`='Manjhi Uttar Tola', `pincode`='841313';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 8, 'Jan Aushadhi Kendra (PMBJK23471) - Sangeeta Gupta', 'जन औषधि केंद्र (PMBJK23471) - Sangeeta Gupta', 'jan-aushadhi-kendra-pmbjk23471', 'Sangeeta Gupta', '18001808080', 'https://janaushadhi.gov.in/', 'Hazari Rajendra Plaza Main Market Taraiyaa Road Beside Old SBI Building Post Amnour', '841401', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK23471) in Saran District. Managed by Sangeeta Gupta. Address: Hazari Rajendra Plaza Main Market Taraiyaa Road Beside Old SBI Building Post Amnour, Pincode: 841401. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK23471) - Sangeeta Gupta', `hindi_title`='जन औषधि केंद्र (PMBJK23471) - Sangeeta Gupta', `address`='Hazari Rajendra Plaza Main Market Taraiyaa Road Beside Old SBI Building Post Amnour', `pincode`='841401';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 15, 'Jan Aushadhi Kendra (PMBJK23630) - Ravi Shankar', 'जन औषधि केंद्र (PMBJK23630) - Ravi Shankar', 'jan-aushadhi-kendra-pmbjk23630', 'Ravi Shankar', '18001808080', 'https://janaushadhi.gov.in/', 'Pir Maker Bazar', '841215', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK23630) in Saran District. Managed by Ravi Shankar. Address: Pir Maker Bazar, Pincode: 841215. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK23630) - Ravi Shankar', `hindi_title`='जन औषधि केंद्र (PMBJK23630) - Ravi Shankar', `address`='Pir Maker Bazar', `pincode`='841215';

INSERT INTO `listings` (`entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `website`, `address`, `pincode`, `business_hours`, `services`, `description`, `is_verified`, `is_featured`, `status`) VALUES
('HEALTHCARE', 12, 268, 9, 'Jan Aushadhi Kendra (PMBJK23766) - Sanjana Kumari', 'जन औषधि केंद्र (PMBJK23766) - Sanjana Kumari', 'jan-aushadhi-kendra-pmbjk23766', 'Sanjana Kumari', '18001808080', 'https://janaushadhi.gov.in/', 'Dhobwal Bazar Near Hanuman Tample', '841403', '8:00 AM - 8:00 PM', 'Generic Medicines, Quality Healthcare Products, Low Cost PMBJK Generic Drugs, Surgical Equipment', 'Official Pradhan Mantri Bhartiya Janaushadhi Kendra (Kendra Code: PMBJK23766) in Saran District. Managed by Sanjana Kumari. Address: Dhobwal Bazar Near Hanuman Tample, Pincode: 841403. Providing high quality generic medicines at affordable prices under the PMBJP initiative by Government of India.', 'YES', 'NO', 'ACTIVE')
ON DUPLICATE KEY UPDATE `category_id`=12, `subcategory_id`=268, `title`='Jan Aushadhi Kendra (PMBJK23766) - Sanjana Kumari', `hindi_title`='जन औषधि केंद्र (PMBJK23766) - Sanjana Kumari', `address`='Dhobwal Bazar Near Hanuman Tample', `pincode`='841403';

