-- SaranIndex.com Schema & Seed Data

-- 1. Blocks Table
CREATE TABLE IF NOT EXISTS `blocks` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `block_name` VARCHAR(100) NOT NULL,
    `hindi_name` VARCHAR(100),
    `slug` VARCHAR(100) UNIQUE,
    `pincode` VARCHAR(10),
    `total_panchayats` INT DEFAULT 0,
    `lgd_code` VARCHAR(20) DEFAULT NULL,
    `census_2001_code` VARCHAR(20) DEFAULT NULL,
    `census_2011_code` VARCHAR(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Panchayats Table
CREATE TABLE IF NOT EXISTS `panchayats` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `block_id` INT NOT NULL,
    `panchayat_name` VARCHAR(100) NOT NULL,
    `hindi_name` VARCHAR(100),
    `slug` VARCHAR(100) UNIQUE,
    FOREIGN KEY (`block_id`) REFERENCES `blocks`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Villages Table
CREATE TABLE IF NOT EXISTS `villages` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `panchayat_id` INT NOT NULL,
    `village_name` VARCHAR(100) NOT NULL,
    `hindi_name` VARCHAR(100),
    `slug` VARCHAR(100) UNIQUE,
    `pincode` VARCHAR(10),
    FOREIGN KEY (`panchayat_id`) REFERENCES `panchayats`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Categories Table
CREATE TABLE IF NOT EXISTS `categories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `hindi_name` VARCHAR(100),
    `icon` VARCHAR(100),
    `slug` VARCHAR(100) UNIQUE,
    `section` ENUM('BUSINESS','PROFESSIONAL','GOVT','EDUCATION','HEALTHCARE','EMERGENCY','BANK','HOTEL') DEFAULT 'BUSINESS',
    `status` ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Subcategories Table
CREATE TABLE IF NOT EXISTS `subcategories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `category_id` INT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `type` ENUM('PROFESSIONAL','BUSINESS') DEFAULT 'PROFESSIONAL',
    `hindi_name` VARCHAR(100),
    `slug` VARCHAR(100) UNIQUE,
    `keywords` TEXT,
    FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Core Listings Table
CREATE TABLE IF NOT EXISTS `listings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `entity_type` ENUM('BUSINESS','PROFESSIONAL','GOVT_OFFICE','SCHOOL_COLLEGE','HEALTHCARE','EMERGENCY','BANK','HOTEL') DEFAULT 'BUSINESS',
    `category_id` INT NOT NULL,
    `subcategory_id` INT DEFAULT NULL,
    `block_id` INT DEFAULT NULL,
    `panchayat_id` INT DEFAULT NULL,
    `village_id` INT DEFAULT NULL,
    `title` VARCHAR(200) NOT NULL,
    `hindi_title` VARCHAR(200),
    `slug` VARCHAR(220) UNIQUE,
    `contact_person` VARCHAR(100),
    `mobile` VARCHAR(20) NOT NULL,
    `mobile_visibility` VARCHAR(20) DEFAULT 'PUBLIC',
    `whatsapp` VARCHAR(20),
    `email` VARCHAR(100),
    `website` VARCHAR(150),
    `address` TEXT,
    `pincode` VARCHAR(10),
    `map_link` TEXT,
    `business_hours` VARCHAR(150) DEFAULT '9:00 AM - 8:00 PM',
    `services` TEXT,
    `products` TEXT,
    `gst_no` VARCHAR(50),
    `udyam_no` VARCHAR(50),
    `cin_no` VARCHAR(50),
    `local_reg_no` VARCHAR(100),
    `description` TEXT,
    `cover_image` VARCHAR(255),
    `is_verified` ENUM('YES','NO') DEFAULT 'NO',
    `is_featured` ENUM('YES','NO') DEFAULT 'NO',
    `status` ENUM('ACTIVE','PENDING','REJECTED') DEFAULT 'ACTIVE',
    `plan_type` ENUM('FREE','GOLD','PLATINUM') DEFAULT 'FREE',
    `plan_expires_at` DATETIME DEFAULT NULL,

    `view_count` INT DEFAULT 0,
    `star_rating` DECIMAL(3,2) DEFAULT 5.00,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`),
    FOREIGN KEY (`block_id`) REFERENCES `blocks`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Reviews Table
CREATE TABLE IF NOT EXISTS `reviews` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `listing_id` INT NOT NULL,
    `reviewer_name` VARCHAR(100) NOT NULL,
    `reviewer_mobile` VARCHAR(20),
    `rating` INT CHECK (rating BETWEEN 1 AND 5),
    `comment` TEXT,
    `status` ENUM('APPROVED','PENDING') DEFAULT 'APPROVED',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`listing_id`) REFERENCES `listings`(`id`) ON DELETE CASCADE
-- 7.5. Public Users Table
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `full_name` VARCHAR(100) NOT NULL,
    `mobile` VARCHAR(20) NOT NULL UNIQUE,
    `whatsapp` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `business_name` VARCHAR(150) DEFAULT NULL,
    `designation` VARCHAR(100) DEFAULT NULL,
    `block_id` INT DEFAULT NULL,
    `panchayat_id` INT DEFAULT NULL,
    `village_id` INT DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    `pincode` VARCHAR(10) DEFAULT NULL,
    `profile_image` VARCHAR(255) DEFAULT NULL,
    `bio` TEXT DEFAULT NULL,
    `status` ENUM('ACTIVE','INACTIVE','SUSPENDED') DEFAULT 'ACTIVE',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `name` VARCHAR(150) DEFAULT NULL,
    `mobile_status` VARCHAR(20) DEFAULT 'UNVERIFIED',
    `mobile_visibility` VARCHAR(20) DEFAULT 'PUBLIC',
    `email_status` VARCHAR(20) DEFAULT 'UNVERIFIED',
    `email_visibility` VARCHAR(20) DEFAULT 'PUBLIC',
    `password` VARCHAR(255) DEFAULT NULL,
    `token` VARCHAR(255) DEFAULT NULL,
    `type` VARCHAR(50) DEFAULT 'USER',
    `address_visibility` VARCHAR(20) DEFAULT 'PUBLIC',
    `state_code` VARCHAR(20) DEFAULT NULL,
    `district_code` VARCHAR(20) DEFAULT NULL,
    `dob` DATE DEFAULT NULL,
    `r_name` VARCHAR(150) DEFAULT NULL,
    `education` VARCHAR(150) DEFAULT NULL,
    `gender` VARCHAR(20) DEFAULT NULL,
    `public_url` VARCHAR(255) DEFAULT NULL,
    `counter` INT DEFAULT 0,
    `univ_code` VARCHAR(50) DEFAULT NULL,
    `college_code` VARCHAR(50) DEFAULT NULL,
    `about` TEXT DEFAULT NULL,
    `photo` VARCHAR(255) DEFAULT NULL,
    `id_proof` VARCHAR(255) DEFAULT NULL,
    `wallet` DECIMAL(10,2) DEFAULT 0.00,
    `created_by` INT DEFAULT 0,
    `updated_by` INT DEFAULT 0,
    `plan_type` VARCHAR(50) DEFAULT NULL,
    `plan_expiry` DATETIME DEFAULT NULL,
    `languages` VARCHAR(255) DEFAULT NULL,
    `otp_code` VARCHAR(20) DEFAULT NULL,
    `otp_expiry` DATETIME DEFAULT NULL,
    `linkedin` VARCHAR(255) DEFAULT NULL,
    `twitter` VARCHAR(255) DEFAULT NULL,
    `facebook` VARCHAR(255) DEFAULT NULL,
    `instagram` VARCHAR(255) DEFAULT NULL,
    `google_maps_link` TEXT DEFAULT NULL,
    FOREIGN KEY (`block_id`) REFERENCES `blocks`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Admins Table
CREATE TABLE IF NOT EXISTS `admins` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `full_name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100),
    `role` ENUM('SUPER_ADMIN','MODERATOR') DEFAULT 'SUPER_ADMIN',
    `last_login` DATETIME NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. Contact Submissions Table
CREATE TABLE IF NOT EXISTS `contact` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(250) NOT NULL,
    `mobile` VARCHAR(20) NOT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `subject` VARCHAR(254) DEFAULT NULL,
    `message` TEXT DEFAULT NULL,
    `mobile_status` VARCHAR(10) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT 'UNREAD',
    `profile_id` INT DEFAULT 0,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `created_by` INT DEFAULT 0,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_by` INT DEFAULT 0,
    `reply` VARCHAR(1000) DEFAULT '',
    `reply_message` TEXT DEFAULT NULL,
    `replied_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. People Table
CREATE TABLE IF NOT EXISTS `people` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `full_name` VARCHAR(120) NOT NULL,
    `hindi_name` VARCHAR(120) DEFAULT NULL,
    `slug` VARCHAR(150) UNIQUE,
    `designation` VARCHAR(100) DEFAULT NULL,
    `profession` VARCHAR(100) DEFAULT NULL,
    `mobile` VARCHAR(20) NOT NULL,
    `whatsapp` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `block_id` INT DEFAULT NULL,
    `panchayat_id` INT DEFAULT NULL,
    `village_id` INT DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    `pincode` VARCHAR(10) DEFAULT NULL,
    `photo` VARCHAR(255) DEFAULT NULL,
    `bio` TEXT DEFAULT NULL,
    `status` ENUM('ACTIVE','PENDING','INACTIVE') DEFAULT 'ACTIVE',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`block_id`) REFERENCES `blocks`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




-- SEED DATA --

-- Seed 20 Blocks of Saran District
INSERT INTO `blocks` (`id`, `block_name`, `hindi_name`, `slug`, `pincode`, `total_panchayats`) VALUES
(1, 'Chapra Sadar', 'छपरा सदर', 'chapra-sadar', '841301', 22),
(2, 'Marhaura', 'मढ़ौरा', 'marhaura', '841418', 18),
(3, 'Sonepur', 'सोनपुर', 'sonepur', '841101', 23),
(4, 'Revelganj', 'रिविलगंज', 'revelganj', '841305', 14),
(5, 'Garkha', 'गरखा', 'garkha', '841311', 20),
(6, 'Parsa', 'परसा', 'parsa', '841219', 16),
(7, 'Dighwara', 'दिघवारा', 'dighwara', '841207', 12),
(8, 'Amanour', 'अमनौर', 'amanour', '841401', 18),
(9, 'Baniapur', 'बनियापुर', 'baniapur', '841403', 24),
(10, 'Ekma', 'एकमा', 'ekma', '841208', 19),
(11, 'Taraiya', 'तरैया', 'taraiya', '841424', 13),
(12, 'Isuapur', 'इसुआपुर', 'isuapur', '841407', 11),
(13, 'Lahladpur', 'लहलादपुर', 'lahladpur', '841408', 9),
(14, 'Manjhi', 'मांझी', 'manjhi', '841313', 24),
(15, 'Maker', 'मेकर', 'maker', '841215', 10),
(16, 'Dariapur', 'दरियापुर', 'dariapur', '841221', 21),
(17, 'Jalalpur', 'जलालपुर', 'jalalpur', '841412', 15),
(18, 'Nagra', 'नगरा', 'nagra', '841442', 12),
(19, 'Mashrakh', 'मशरख', 'mashrakh', '841417', 16),
(20, 'Panapur', 'पन्नापुर', 'panapur', '841410', 11)
ON DUPLICATE KEY UPDATE `block_name` = VALUES(`block_name`);

-- Seed Panchayats for Chapra Sadar
INSERT INTO `panchayats` (`id`, `block_id`, `panchayat_name`, `hindi_name`, `slug`) VALUES
(1, 1, 'Dahiyawan', 'दहियावां', 'dahiyawan'),
(2, 1, 'Sahebganj', 'साहिबगंज', 'sahebganj'),
(3, 1, 'Bhagwan Bazar', 'भगवान बाजार', 'bhagwan-bazar'),
(4, 1, 'Mouna', 'मौना', 'mouna'),
(5, 2, 'Marhaura North', 'मढ़ौरा उत्तर', 'marhaura-north'),
(6, 3, 'Govindpur Sonepur', 'गोविंदपुर सोनपुर', 'govindpur-sonepur')
ON DUPLICATE KEY UPDATE `panchayat_name` = VALUES(`panchayat_name`);

-- Seed Categories (Core Verticals)
INSERT INTO `categories` (`id`, `name`, `hindi_name`, `icon`, `slug`, `section`) VALUES
(1, 'AI Services', 'एआई सेवाएं व स्मार्ट सहायता', 'bi-robot', 'ai-services', 'BUSINESS'),
(2, 'Agriculture', 'कृषि व पशुपालन', 'bi-flower1', 'agriculture', 'BUSINESS'),
(3, 'Automobile', 'ऑटोमोबाइल व वाहन', 'bi-car-front', 'automobile', 'BUSINESS'),
(4, 'Business and Services', 'व्यापार एवं सेवाएं', 'bi-shop', 'business-services', 'BUSINESS'),
(5, 'Classifieds', 'वर्गीकृत विज्ञापन', 'bi-grid', 'classifieds', 'BUSINESS'),
(6, 'Education', 'शिक्षा', 'bi-mortarboard', 'education', 'EDUCATION'),
(7, 'Entertainment', 'मनोरंजन व कला', 'bi-film', 'entertainment', 'BUSINESS'),
(8, 'Events', 'कार्यक्रम व आयोजन', 'bi-calendar-event', 'events', 'BUSINESS'),
(9, 'Finance', 'वित्त व बैंकिंग', 'bi-bank', 'finance', 'BANK'),
(10, 'Food and Restaurants', 'खान-पान व रेस्टोरेंट', 'bi-cup-hot', 'food-restaurants', 'HOTEL'),
(11, 'Government', 'सरकारी कार्यालय', 'bi-building', 'government', 'GOVT'),
(12, 'Health', 'स्वास्थ्य एवं चिकित्सा', 'bi-hospital', 'health', 'HEALTHCARE'),
(13, 'Home Services', 'होम सर्विसेज व मरम्मत', 'bi-tools', 'home-services', 'BUSINESS'),
(14, 'Hotels and Tourism', 'होटल व पर्यटन', 'bi-building-check', 'hotels-tourism', 'HOTEL'),
(15, 'Industrial', 'उद्योग व निर्माण', 'bi-gear-wide-connected', 'industrial', 'BUSINESS'),
(16, 'Jobs and Career', 'नौकरी एवं करियर', 'bi-briefcase', 'jobs-career', 'PROFESSIONAL'),
(17, 'Legal', 'कानूनी सेवाएं', 'bi-journal-text', 'legal', 'PROFESSIONAL'),
(18, 'Local Information', 'स्थानीय सूचना व निर्देशिका', 'bi-info-circle', 'local-information', 'BUSINESS'),
(19, 'NGOs and Social', 'एनजीओ व समाज सेवा', 'bi-people', 'ngos-social', 'BUSINESS'),
(20, 'News and Media', 'समाचार व मीडिया', 'bi-newspaper', 'news-media', 'BUSINESS'),
(21, 'Other', 'अन्य सेवाएं व विविध', 'bi-three-dots', 'other', 'BUSINESS'),
(22, 'Pets and Animals', 'पशु-पक्षी व पेट्स', 'bi-heart-pulse', 'pets-animals', 'BUSINESS'),
(23, 'Professional Services', 'व्यावसायिक सेवाएं', 'bi-person-gear', 'professional-services', 'PROFESSIONAL'),
(24, 'Property', 'प्रॉपर्टी व प्रॉपर्टी डीलर', 'bi-house-check', 'property', 'BUSINESS'),
(25, 'Religion', 'धार्मिक व आध्यात्मिक', 'bi-brightness-high', 'religion', 'BUSINESS'),
(26, 'Shopping', 'खरीददारी व दुकानें', 'bi-bag', 'shopping', 'BUSINESS'),
(27, 'Sports and Fitness', 'खेल-कूद व फिटनेस', 'bi-activity', 'sports-fitness', 'BUSINESS'),
(28, 'Technology', 'तकनीक व आईटी', 'bi-laptop', 'technology', 'BUSINESS'),
(29, 'Transport', 'परिवहन व यात्रा', 'bi-truck', 'transport', 'BUSINESS')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- Seed Subcategories (Standalone Entities, Professional FIRST then Business, Sorted Alphabetically)
INSERT INTO `subcategories` (`id`, `category_id`, `name`, `type`, `hindi_name`, `slug`, `keywords`) VALUES
(1, 1, 'AI Chat Assistant', 'PROFESSIONAL', 'एआई चैट सहायक', 'ai-chat-assistant', 'ai chatbot, virtual assistant'),
(2, 1, 'AI Search', 'PROFESSIONAL', 'एआई खोज', 'ai-search', 'ai search, smart search assistant'),
(3, 1, 'Business Assistant', 'PROFESSIONAL', 'व्यापार सहायक', 'business-assistant', 'ai business advisor'),
(4, 1, 'Government Help', 'PROFESSIONAL', 'सरकारी सहायता गाइड', 'government-help', 'ai scheme helper'),
(5, 1, 'Local Recommendation Engine', 'PROFESSIONAL', 'स्थानीय सुझाव इंजन', 'local-recommendation-engine', 'local recommendations'),
(6, 1, 'Tourist Guide', 'PROFESSIONAL', 'पर्यटन गाइड', 'tourist-guide', 'ai tourist guide'),
(7, 2, 'Farmers', 'PROFESSIONAL', 'किसान व कृषक', 'farmers', 'farmer, kisan, organic farmer'),
(8, 2, 'Farming Labours and Workers', 'PROFESSIONAL', 'कृषि मजदूर व खेतिहर श्रमिक', 'farming-labours-workers', 'farming labour, kheti mazdoor, agricultural worker, khet majdoor'),
(9, 2, 'Veterinary Doctors', 'PROFESSIONAL', 'पशु चिकित्सक', 'agri-veterinary-doctors', 'pashu doctor, veterinary doctor'),
(10, 2, 'Dairy', 'BUSINESS', 'डेयरी फार्म व दुग्ध केंद्र', 'dairy', 'dairy farm, sudha milk booth'),
(11, 2, 'Farm Equipment', 'BUSINESS', 'कृषि यंत्र डीलर', 'farm-equipment', 'tractor dealer, thresher'),
(12, 2, 'Fertilizer Shops', 'BUSINESS', 'खाद व कीटनाशक दुकान', 'fertilizer-shops', 'khad dukan, fertilizer store'),
(13, 2, 'Fisheries', 'BUSINESS', 'मत्स्य पालन', 'fisheries', 'machhli palan, fish farm'),
(14, 2, 'Poultry', 'BUSINESS', 'पोल्ट्री फार्म व पशु आहार', 'poultry', 'poultry farm, murgi farm'),
(15, 2, 'Seed Dealers', 'BUSINESS', 'बीज विक्रेता', 'seed-dealers', 'seed dealer, beej dukan'),
(16, 3, 'Bike Mechanics', 'PROFESSIONAL', 'बाइक मैकेनिक', 'bike-mechanics', 'bike mechanic, motorcycle repair'),
(17, 3, 'Car Mechanics', 'PROFESSIONAL', 'कार मैकेनिक', 'car-mechanics', 'car mechanic, car garage, motor mistri'),
(18, 3, 'Driving Instructors', 'PROFESSIONAL', 'ड्राइविंग इंस्ट्रक्टर', 'driving-instructors', 'driving instructor, motor driving trainer'),
(19, 3, 'Bike Dealers', 'BUSINESS', 'बाइक डीलर व शो-रूम', 'bike-dealers', 'hero showroom, honda showroom'),
(20, 3, 'Car Dealers', 'BUSINESS', 'कार डीलर व शो-रूम', 'car-dealers', 'car dealer, car showroom'),
(21, 3, 'Driving Schools', 'BUSINESS', 'ड्राइविंग स्कूल', 'driving-schools', 'driving school, motor driving'),
(22, 3, 'EV Charging Stations', 'BUSINESS', 'ईवी चार्जिंग स्टेशन', 'ev-charging-stations', 'ev charging, electric vehicle charger'),
(23, 3, 'Petrol Pumps', 'BUSINESS', 'पेट्रोल पंप', 'petrol-pumps', 'petrol pump, indian oil, hp petrol pump'),
(24, 3, 'Service Centres', 'BUSINESS', 'सर्विस सेंटर', 'service-centres', 'bike service center, car service station'),
(25, 3, 'Spare Parts', 'BUSINESS', 'स्पेयर पार्ट्स', 'spare-parts', 'auto spare parts, bike parts'),
(26, 4, 'Moving Shops and Chalant Dukan', 'PROFESSIONAL', 'चलंत दुकान व ठेला वेंडर', 'moving-shops-chalant-dukan', 'chalant dukan, moving shop, cart vendor'),
(27, 4, 'Service Providers', 'PROFESSIONAL', 'सेवा प्रदाता', 'biz-service-providers', 'service provider, freelancer, consultant'),
(28, 4, 'Street Hawkers and Pheriwala', 'PROFESSIONAL', 'फेरीवाला व घुमंतू विक्रेता', 'street-hawkers-pheriwala', 'pheriwala, hawker, street vendor, ghumantu dukan'),
(29, 4, 'Business Directory', 'BUSINESS', 'बिजनेस डायरेक्टरी', 'business-directory', 'business directory, company listing'),
(30, 4, 'Franchise Opportunities', 'BUSINESS', 'फ्रैंचाइज़ी अवसर', 'franchise-opportunities', 'franchise, dealership'),
(31, 4, 'MSMEs', 'BUSINESS', 'एमएसएमई', 'msmes', 'msme, micro small medium enterprise'),
(32, 4, 'Manufacturers', 'BUSINESS', 'निर्माता व उद्योग', 'manufacturers', 'manufacturer, factory owner'),
(33, 4, 'Retail Shops', 'BUSINESS', 'खुदरा दुकान', 'retail-shops', 'retail store, shop, dukan'),
(34, 4, 'Startups', 'BUSINESS', 'स्टार्टअप्स', 'startups', 'tech startup, new business'),
(35, 4, 'Wholesalers', 'BUSINESS', 'थोक विक्रेता', 'wholesalers', 'wholesaler, bulk dealer'),
(36, 5, 'Buy and Sell', 'PROFESSIONAL', 'खरीदें व बेचें', 'buy-sell', 'buy sell, old goods'),
(37, 5, 'Lost and Found', 'PROFESSIONAL', 'खोया-पाया', 'lost-found', 'lost and found, missing item'),
(38, 5, 'Auctions', 'BUSINESS', 'नीलामी', 'auctions', 'auction, bank auction'),
(39, 5, 'Second-hand Goods', 'BUSINESS', 'पुराना सामान', 'second-hand-goods', 'used bike, used mobile'),
(40, 5, 'Tenders', 'BUSINESS', 'टेंडर', 'tenders', 'government tender'),
(41, 6, 'Career Counselors', 'PROFESSIONAL', 'करियर काउंसलर', 'career-counselors', 'career guidance, student counselor'),
(42, 6, 'Home Tutors and Home Tuition', 'PROFESSIONAL', 'होम ट्यूटर व होम ट्यूशन', 'home-tutors-tuition', 'home tutor, home tuition, private home teacher'),
(43, 6, 'Professors and Lecturers', 'PROFESSIONAL', 'प्रोफेसर एवं व्याख्याता', 'professors-lecturers', 'professor, lecturer, college faculty'),
(44, 6, 'Tutors and Private Teachers', 'PROFESSIONAL', 'व्यक्तिगत शिक्षक व ट्यूटर', 'tutors-private-teachers', 'tutor, home tutor, private teacher'),
(45, 6, 'Coaching Institutes', 'BUSINESS', 'कोचिंग संस्थान', 'coaching-institutes', 'coaching, competitive exam, iit jee, neet'),
(46, 6, 'Colleges', 'BUSINESS', 'कॉलेज व महाविधालय', 'colleges', 'college, degree college, inter college'),
(47, 6, 'Hostels', 'BUSINESS', 'छात्रावास व पीजी', 'hostels', 'hostel, student pg'),
(48, 6, 'Libraries', 'BUSINESS', 'पुस्तकालय व स्टडी रूम', 'libraries', 'library, study room'),
(49, 6, 'Online Courses', 'BUSINESS', 'ऑनलाइन कोर्स व डिजिटल क्लास', 'online-courses', 'online course, digital class'),
(50, 6, 'Schools', 'BUSINESS', 'स्कूल व विद्यालय', 'schools', 'school, primary school, high school'),
(51, 6, 'Skill Development Centres', 'BUSINESS', 'कौशल विकास केंद्र', 'skill-development-centres', 'skill training, kushal yuva program'),
(52, 6, 'Tuition Centres', 'BUSINESS', 'ट्यूशन सेंटर', 'tuition-centres', 'tuition, coaching, math tuition'),
(53, 6, 'Universities', 'BUSINESS', 'विश्वविद्यालय', 'universities', 'university, jp university'),
(54, 7, 'Music and Dance Teachers', 'PROFESSIONAL', 'संगीत व नृत्य शिक्षक', 'music-dance-teachers', 'music teacher, dance teacher'),
(55, 7, 'Photographers and Videographers', 'PROFESSIONAL', 'फोटोग्राफर व वीडियोग्राफर', 'photographers-videographers', 'photographer, videographer, studio'),
(56, 7, 'Cinema Halls', 'BUSINESS', 'सिनेमा हॉल', 'cinema-halls', 'cinema hall, talkies, movie theater'),
(57, 7, 'Clubs', 'BUSINESS', 'क्लब', 'clubs', 'recreation club, sports club'),
(58, 7, 'Event Venues', 'BUSINESS', 'इवेंट स्थल', 'event-venues', 'event venue, open lawn'),
(59, 7, 'Gaming Zones', 'BUSINESS', 'गेमिंग जोन', 'gaming-zones', 'gaming zone, playstation parlor'),
(60, 8, 'Event Managers and Organizers', 'PROFESSIONAL', 'इवेंट मैनेजर', 'event-managers', 'event manager, party planner'),
(61, 8, 'Conferences', 'BUSINESS', 'सम्मेलन', 'conferences', 'conference, business meeting'),
(62, 8, 'Cultural Programs', 'BUSINESS', 'सांस्कृतिक कार्यक्रम', 'cultural-programs', 'cultural show, sangeet program'),
(63, 8, 'Exhibitions', 'BUSINESS', 'प्रदर्शनी', 'exhibitions', 'exhibition, trade fair'),
(64, 8, 'Fairs', 'BUSINESS', 'मेले', 'fairs', 'mela, sonepur mela'),
(65, 8, 'Local Events', 'BUSINESS', 'स्थानीय कार्यक्रम', 'local-events', 'local event, cultural function'),
(66, 8, 'Sports Events', 'BUSINESS', 'खेल-कूद प्रतियोगिता', 'sports-events', 'cricket match, tournament'),
(67, 8, 'Weddings', 'BUSINESS', 'विवाह भवन व मैरिज हॉल', 'weddings', 'vivah bhawan, marriage hall'),
(68, 9, 'Chartered Accountants', 'PROFESSIONAL', 'चार्टर्ड अकाउंटेंट (CA)', 'chartered-accountants', 'ca, chartered accountant, audit'),
(69, 9, 'Digital Banking Agents / CSP', 'PROFESSIONAL', 'सीएसपी केंद्र', 'digital-banking-csp', 'csp agent, aeps agent'),
(70, 9, 'Financial Advisors', 'PROFESSIONAL', 'वित्तीय सलाहकार', 'financial-advisors', 'financial advisor, investment advisor'),
(71, 9, 'Insurance Agents', 'PROFESSIONAL', 'बीमा एजेंट', 'insurance-agents', 'lic agent, life insurance agent'),
(72, 9, 'Tax Consultants', 'PROFESSIONAL', 'टैक्स कंसलटेंट', 'finance-tax-consultants', 'tax consultant, gst advocate'),
(73, 9, 'ATMs', 'BUSINESS', 'एटीएम', 'atms', 'atm, cash deposit machine'),
(74, 9, 'Banks', 'BUSINESS', 'बैंक', 'banks', 'sbi, pnb, hdfc bank'),
(75, 9, 'Loan Services', 'BUSINESS', 'ऋण सेवाएं', 'loan-services', 'personal loan, home loan agent'),
(76, 9, 'Mutual Funds', 'BUSINESS', 'म्यूचुअल फंड', 'mutual-funds', 'mutual fund advisor, sip'),
(77, 10, 'Catering Services', 'PROFESSIONAL', 'केटरिंग सेवा', 'food-catering-services', 'catering service, party caterer'),
(78, 10, 'Chefs and Halwai', 'PROFESSIONAL', 'शेफ व हलवाई', 'chefs-halwai', 'chef, halwai, sweet cook'),
(79, 10, 'Street Food', 'PROFESSIONAL', 'स्ट्रीट फूड व ठेला दुकान', 'street-food', 'litti chokha, chaat stall, food cart'),
(80, 10, 'Bakeries', 'BUSINESS', 'बेकरी', 'bakeries', 'bakery, cake shop, pastry'),
(81, 10, 'Cafes', 'BUSINESS', 'कैफे', 'cafes', 'cafe, coffee shop, tea lounge'),
(82, 10, 'Fast Food', 'BUSINESS', 'फास्ट फूड दुकान', 'fast-food', 'fast food corner, burger pizza'),
(83, 10, 'Hotels', 'BUSINESS', 'होटल व लॉज', 'food-hotels', 'hotel, lodge, room stay'),
(84, 10, 'Restaurants', 'BUSINESS', 'रेस्टोरेंट', 'restaurants', 'restaurant, family dining, dhaba'),
(85, 10, 'Sweet Shops', 'BUSINESS', 'मिठाई की दुकान', 'sweet-shops', 'sweet shop, mithai dukan, rasgulla'),
(86, 11, 'District Administration', 'PROFESSIONAL', 'जिला प्रशासन', 'district-administration', 'collectorate, district magistrate'),
(87, 11, 'Municipal Services', 'PROFESSIONAL', 'नगर निगम व परिषद', 'municipal-services', 'nagar nigam chapra, holding tax'),
(88, 11, 'Public Service Centres', 'PROFESSIONAL', 'वसुधा केंद्र व आरटीपीएस', 'public-service-centres', 'vasudha kendra, rtps, csc'),
(89, 11, 'Fire Stations', 'BUSINESS', 'फायर स्टेशन', 'fire-stations', 'fire station, fire brigade 101'),
(90, 11, 'Government Offices', 'BUSINESS', 'सरकारी कार्यालय', 'government-offices', 'dm office, sdo office, bdo office'),
(91, 11, 'Panchayats', 'BUSINESS', 'पंचायत भवन', 'panchayats', 'panchayat bhawan, mukhiya office'),
(92, 11, 'Police Stations', 'BUSINESS', 'पुलिस थाना व ओपी', 'police-stations', 'police station, thana, op'),
(93, 12, 'Ambulance', 'PROFESSIONAL', 'एंबुलेंस सेवा', 'ambulance', 'ambulance, 102 ambulance'),
(94, 12, 'Ayurvedic Doctors', 'PROFESSIONAL', 'आयुर्वेदिक डॉक्टर', 'ayurvedic-doctors', 'ayurveda doctor, vaidya'),
(95, 12, 'Dentists', 'PROFESSIONAL', 'दंत चिकित्सक', 'dentists', 'dentist, dental clinic, root canal'),
(96, 12, 'Doctors', 'PROFESSIONAL', 'डॉक्टर एवं विशेषज्ञ', 'doctors', 'doctor, physician, surgeon, opd doctor'),
(97, 12, 'Eye Doctors', 'PROFESSIONAL', 'नेत्र चिकित्सक', 'eye-doctors', 'eye doctor, ophthalmologist'),
(98, 12, 'Homeopathy Doctors', 'PROFESSIONAL', 'होम्योपैथी डॉक्टर', 'homeopathy-doctors', 'homeopathy doctor, homeopathic clinic'),
(99, 12, 'Nurses', 'PROFESSIONAL', 'नर्स एवं स्वास्थ्य कर्मी', 'nurses', 'nurse, home nurse, paramedic'),
(100, 12, 'Veterinary Doctors', 'PROFESSIONAL', 'पशु चिकित्सक', 'health-veterinary-doctors', 'veterinary doctor, pashu doctor'),
(101, 12, 'Blood Banks', 'BUSINESS', 'ब्लड बैंक', 'blood-banks', 'blood bank, blood donation'),
(102, 12, 'Clinics', 'BUSINESS', 'क्लीनिक व ओपीडी', 'clinics', 'clinic, opd clinic'),
(103, 12, 'Diagnostic Centres', 'BUSINESS', 'जांच केंद्र व पैथोलॉजी', 'diagnostic-centres', 'diagnostic lab, blood test, pathology'),
(104, 12, 'Hospitals', 'BUSINESS', 'अस्पताल', 'hospitals', 'hospital, sadar hospital, private hospital'),
(105, 12, 'Pharmacies', 'BUSINESS', 'दवा की दुकानें', 'pharmacies', 'medical store, pharmacy, dawa dukan'),
(106, 12, 'Veterinary Clinics', 'BUSINESS', 'पशु चिकित्सालय', 'health-veterinary-clinics', 'pashu hospital, veterinary clinic'),
(107, 13, 'AC Repair Technicians', 'PROFESSIONAL', 'एसी रिपेयर तकनीशियन', 'ac-repair-technicians', 'ac repair, ac servicing'),
(108, 13, 'Appliance Mechanics', 'PROFESSIONAL', 'फ्रिज व वाशिंग मशीन मैकेनिक', 'appliance-mechanics', 'fridge repair, washing machine repair'),
(109, 13, 'Carpenters', 'PROFESSIONAL', 'कारपेंटर व बढ़ई', 'carpenters', 'carpenter, furniture repair'),
(110, 13, 'Centering and Shuttering Workers', 'PROFESSIONAL', 'सेंटरिंग व शटरिंग कारीगर', 'centering-shuttering-workers', 'centering mistri, shuttering worker, lenter mistri'),
(111, 13, 'Construction Contractors and Builders', 'PROFESSIONAL', 'निर्माण ठेकेदार व बिल्डर', 'home-construction-contractors', 'construction contractor, building contractor, makan thekedar, contractor'),
(112, 13, 'Construction Labours and Helpers', 'PROFESSIONAL', 'निर्माण मजदूर व बेलदार', 'construction-labours-helpers', 'construction labour, beldar, construction worker, majdoor'),
(113, 13, 'Electricians', 'PROFESSIONAL', 'इलेक्ट्रीशियन', 'electricians', 'electrician, bijli mistri'),
(114, 13, 'Home Cleaners', 'PROFESSIONAL', 'होम क्लीनर', 'home-cleaners', 'house cleaning, tank cleaning'),
(115, 13, 'Masons and Raj Mistri', 'PROFESSIONAL', 'राजमिस्त्री व निर्माण कारीगर', 'masons-raj-mistri', 'raj mistri, mason, rajmistri, makan mistri, construction mason'),
(116, 13, 'Painters', 'PROFESSIONAL', 'पेंटर व पुट्टी कारीगर', 'painters', 'painter, house painter'),
(117, 13, 'Pest Control Experts', 'PROFESSIONAL', 'पेस्ट कंट्रोल एक्सपर्ट', 'pest-control-experts', 'pest control, termite control'),
(118, 13, 'Plumbers', 'PROFESSIONAL', 'प्लंबर', 'plumbers', 'plumber, pipe fitting'),
(119, 13, 'Tiles, Marble and Flooring Workers', 'PROFESSIONAL', 'टाइल्स व मार्बल मिस्त्री', 'tiles-marble-flooring-workers', 'tile mistri, marble mistri, flooring worker'),
(120, 14, 'Tour Operators', 'PROFESSIONAL', 'टूर ऑपरेटर व एजेंसी', 'tour-operators', 'tour operator, travel agency'),
(121, 14, 'Travel Guides', 'PROFESSIONAL', 'टूर गाइड व गाइड', 'travel-guides', 'tour guide, travel guide'),
(122, 14, 'Heritage Sites', 'BUSINESS', 'ऐतिहासिक स्थल', 'heritage-sites', 'historical place, heritage site'),
(123, 14, 'Homestays', 'BUSINESS', 'होमस्टे', 'homestays', 'homestay, village stay'),
(124, 14, 'Hotels', 'BUSINESS', 'होटल', 'tourism-hotels', 'hotel, ac room hotel'),
(125, 14, 'Lodges', 'BUSINESS', 'लॉज', 'lodges', 'lodge, cheap lodge'),
(126, 14, 'Parks', 'BUSINESS', 'पार्क', 'parks', 'public park, garden, eco park'),
(127, 14, 'Religious Places', 'BUSINESS', 'धार्मिक स्थल', 'religious-places', 'mandir, masjid, gurudwara'),
(128, 14, 'Resorts', 'BUSINESS', 'रिसोर्ट', 'resorts', 'resort, holiday resort'),
(129, 14, 'Tourist Attractions', 'BUSINESS', 'पर्यटन स्थल', 'tourist-attractions', 'tourist spot, aami temple, chirand'),
(130, 15, 'Exporters', 'PROFESSIONAL', 'निर्यातक', 'exporters', 'exporter, export agency'),
(131, 15, 'Importers', 'PROFESSIONAL', 'आयातकर्ता', 'importers', 'importer, import agent'),
(132, 15, 'Industrial Consultants and Suppliers', 'PROFESSIONAL', 'औद्योगिक आपूर्तिकर्ता', 'industrial-suppliers', 'industrial supplier, raw material supplier'),
(133, 15, 'Factories', 'BUSINESS', 'फैक्टरियां', 'factories', 'factory, manufacturing plant'),
(134, 15, 'Industrial Areas', 'BUSINESS', 'औद्योगिक क्षेत्र', 'industrial-areas', 'industrial area, marhaura industrial estate'),
(135, 15, 'Warehouses', 'BUSINESS', 'गोदाम व वेयरहाउस', 'warehouses', 'godown, warehouse, cold storage'),
(136, 16, 'Career Guidance Experts', 'PROFESSIONAL', 'करियर गाइडेंस एक्सपर्ट', 'career-guidance-experts', 'career guidance, student counselor'),
(137, 16, 'Resume Consultants', 'PROFESSIONAL', 'रेज़्यूमे कंसलटेंट', 'resume-consultants', 'resume writer, cv designer'),
(138, 16, 'Government Jobs', 'BUSINESS', 'सरकारी नौकरियां', 'government-jobs', 'sarkari naukri, bpsc, ssc'),
(139, 16, 'Internships', 'BUSINESS', 'इन्टर्नशिप', 'internships', 'internship, fresher job'),
(140, 16, 'Private Jobs', 'BUSINESS', 'निजी नौकरियां', 'private-jobs', 'private job, local vacancy, office job'),
(141, 16, 'Recruitment Agencies', 'BUSINESS', 'भर्ती एजेंसियां', 'recruitment-agencies', 'job placement agency, hiring agency'),
(142, 16, 'Walk-in Interviews', 'BUSINESS', 'वॉक-इन इंटरव्यू', 'walk-in-interviews', 'walkin interview, urgent hiring'),
(143, 17, 'Advocate Clerks and Munshi', 'PROFESSIONAL', 'एडवोकेट क्लर्क व मुंशी', 'advocate-clerks-munshi', 'advocate clerk, munshi, vakil clerk, law clerk, court clerk'),
(144, 17, 'Advocates', 'PROFESSIONAL', 'वकील व एडवोकेट', 'advocates', 'advocate, lawyer, court lawyer'),
(145, 17, 'Civil Lawyers', 'PROFESSIONAL', 'सिविल वकील', 'civil-lawyers', 'civil lawyer, property lawyer'),
(146, 17, 'Criminal Lawyers', 'PROFESSIONAL', 'क्रिमिनल वकील', 'criminal-lawyers', 'criminal lawyer, bail lawyer'),
(147, 17, 'Document Writers / Katib', 'PROFESSIONAL', 'कातिब व दस्तावेज लेखक', 'document-writers-katib', 'katib, document writer, deed writer'),
(148, 17, 'Family Lawyers', 'PROFESSIONAL', 'पारिवारिक वकील', 'family-lawyers', 'family lawyer, divorce lawyer'),
(149, 17, 'Land Dispute Lawyers', 'PROFESSIONAL', 'भूमि विवाद वकील', 'land-dispute-lawyers', 'land dispute lawyer, mutation lawyer'),
(150, 17, 'Legal Services', 'PROFESSIONAL', 'कानूनी परामर्श सेवाएं', 'legal-services', 'legal services, legal advisor'),
(151, 17, 'Mediators', 'PROFESSIONAL', 'मध्यस्थ व सुलहकर्ता', 'mediators', 'mediator, arbitrator'),
(152, 17, 'Notaries', 'PROFESSIONAL', 'नोटरी पब्लिक', 'notaries', 'notary, affidavit'),
(153, 17, 'Tax Consultants', 'PROFESSIONAL', 'टैक्स कंसलटेंट', 'legal-tax-consultants', 'tax consultant, gst advocate'),
(154, 17, 'Bar Associations', 'BUSINESS', 'बार एसोसिएशन', 'bar-associations', 'bar association'),
(155, 17, 'Courts', 'BUSINESS', 'अदालत व कोर्ट', 'courts', 'civil court, district court'),
(156, 17, 'Law Firms', 'BUSINESS', 'लॉ फर्म', 'law-firms', 'law firm, legal consultancy'),
(157, 17, 'Legal Aid', 'BUSINESS', 'विधिक सहायता', 'legal-aid', 'legal aid, free legal help'),
(158, 18, 'Emergency Contacts', 'PROFESSIONAL', 'आपातकालीन संपर्क', 'emergency-contacts', 'emergency number, helpline 112'),
(159, 18, 'Block Directory', 'BUSINESS', 'प्रखंड निर्देशिका', 'block-directory', 'block list saran'),
(160, 18, 'District Map', 'BUSINESS', 'जिला मानचित्र', 'district-map', 'saran district map'),
(161, 18, 'Festivals', 'BUSINESS', 'त्यौहार', 'festivals', 'chhat puja, sonepur mela'),
(162, 18, 'PIN Codes', 'BUSINESS', 'पिन कोड', 'pin-codes', 'pin code chapra, saran pincodes'),
(163, 18, 'Public Holidays', 'BUSINESS', 'सार्वजनिक अवकाश', 'public-holidays', 'govt holiday list'),
(164, 18, 'Village Directory', 'BUSINESS', 'ग्राम निर्देशिका', 'village-directory', 'village directory, gram panchayat list'),
(165, 18, 'Ward Directory', 'BUSINESS', 'वार्ड निर्देशिका', 'ward-directory', 'ward councillor, ward list'),
(166, 18, 'Weather', 'BUSINESS', 'मौसम', 'weather', 'saran weather, chapra temperature'),
(167, 19, 'Social Workers and Volunteers', 'PROFESSIONAL', 'समाजसेवी व वालंटियर', 'social-workers-volunteers', 'social worker, volunteer'),
(168, 19, 'Charities', 'BUSINESS', 'चैरिटी व ट्रस्ट', 'charities', 'charity, public trust'),
(169, 19, 'Community Organizations', 'BUSINESS', 'सामुदायिक संगठन', 'community-organizations', 'community group, samajik sangathan'),
(170, 19, 'NGOs', 'BUSINESS', 'एनजीओ', 'ngos', 'ngo, non profit organization'),
(171, 19, 'Self Help Groups', 'BUSINESS', 'स्वयं सहायता समूह (जीविका)', 'self-help-groups', 'shg, jeevika group'),
(172, 20, 'Content Creators and Podcasters', 'PROFESSIONAL', 'कंटेंट क्रिएटर व पॉडकास्टर', 'content-creators-podcasters', 'content creator, podcaster, voice artist'),
(173, 20, 'Journalists and Reporters', 'PROFESSIONAL', 'पत्रकार व रिपोर्टर', 'journalists-reporters', 'journalist, reporter, press reporter'),
(174, 20, 'Local News', 'BUSINESS', 'स्थानीय समाचार डिजिटल', 'local-news', 'local news, saran news portal'),
(175, 20, 'Magazines', 'BUSINESS', 'पत्रिकाएं', 'magazines', 'magazine, journal'),
(176, 20, 'Newspapers', 'BUSINESS', 'दैनिक समाचार पत्र', 'newspapers', 'dainik jagran, prabhat khabar'),
(177, 20, 'Podcasts', 'BUSINESS', 'पॉडकास्ट', 'podcasts', 'podcast channel'),
(178, 20, 'Press Releases', 'BUSINESS', 'प्रेस विज्ञप्ति', 'press-releases', 'press note, press release'),
(179, 20, 'Radio', 'BUSINESS', 'रेडियो', 'radio', 'radio station, fm radio'),
(180, 20, 'YouTube Channels', 'BUSINESS', 'यूट्यूब चैनल', 'youtube-channels', 'youtube news channel'),
(181, 21, 'Other', 'PROFESSIONAL', 'अन्य सेवाएं व विविध', 'other-services', 'other, miscellanous, unclassified'),
(182, 22, 'Pet Groomers', 'PROFESSIONAL', 'पेट ग्रूमर व केयरटेकर', 'pet-groomers', 'pet groomer, dog trainer'),
(183, 22, 'Veterinary Doctors', 'PROFESSIONAL', 'पशु डॉक्टर', 'pets-vet-doctors', 'veterinary doctor, pashu doctor'),
(184, 22, 'Animal Shelters', 'BUSINESS', 'पशु आश्रय', 'animal-shelters', 'animal shelter, gaushala'),
(185, 22, 'Pet Shops', 'BUSINESS', 'पेट शॉप', 'pet-shops', 'pet shop, dog food'),
(186, 22, 'Veterinary Hospitals', 'BUSINESS', 'पशु अस्पताल', 'pets-veterinary-hospitals', 'pashu hospital, vet hospital'),
(187, 23, 'Architects', 'PROFESSIONAL', 'वास्तुकार', 'prof-architects', 'architect, house map'),
(188, 23, 'Consultants', 'PROFESSIONAL', 'कंसलटेंट', 'prof-consultants', 'business consultant, legal consultant'),
(189, 23, 'Engineers', 'PROFESSIONAL', 'सिविल व स्ट्रक्चर इंजीनियर', 'prof-engineers', 'civil engineer, structure engineer'),
(190, 23, 'Event Planners', 'PROFESSIONAL', 'इवेंट प्लानर', 'prof-event-planners', 'event planner, party manager'),
(191, 23, 'Interior Designers', 'PROFESSIONAL', 'इंटीरियर डिजाइनर', 'prof-interior-designers', 'interior designer, modular kitchen'),
(192, 23, 'Marketing Agencies', 'BUSINESS', 'मार्केटिंग एजेंसी', 'prof-marketing-agencies', 'digital marketing, ad agency'),
(193, 24, 'Construction Contractors and Builders', 'PROFESSIONAL', 'निर्माण ठेकेदार व बिल्डर', 'construction-contractors-builders', 'construction contractor, builder, makan thekedar, civil contractor'),
(194, 24, 'Property Valuation Experts', 'PROFESSIONAL', 'प्रॉपर्टी वैल्यूअर', 'property-valuation-experts', 'property valuer, land valuer'),
(195, 24, 'Real Estate Agents', 'PROFESSIONAL', 'प्रॉपर्टी एजेंट व ब्रोकर', 'real-estate-agents', 'property dealer, land broker, plot dealer'),
(196, 24, 'Agricultural Land', 'BUSINESS', 'कृषि योग्य भूमि', 'agricultural-land', 'khet for sale, farm land'),
(197, 24, 'Commercial Property', 'BUSINESS', 'किराये व बिक्री की दुकान व ऑफिस', 'commercial-property', 'shop for rent, office space'),
(198, 24, 'Residential Rent', 'BUSINESS', 'किराये का मकान व रूम', 'residential-rent', 'house for rent, room for rent'),
(199, 24, 'Residential Sale', 'BUSINESS', 'बिक्री हेतु मकान व प्लॉट', 'residential-sale', 'plot for sale, house for sale'),
(200, 25, 'Priests and Astrologers', 'PROFESSIONAL', 'पंडित, पुजारी व ज्योतिषी', 'priests-astrologers', 'pandit, pujari, astrologer, jyotish'),
(201, 25, 'Ashrams', 'BUSINESS', 'आश्रम', 'ashrams', 'ashram, spiritual retreat'),
(202, 25, 'Churches', 'BUSINESS', 'चर्च', 'churches', 'church, christian church'),
(203, 25, 'Gurudwaras', 'BUSINESS', 'गुरुद्वारा', 'gurudwaras', 'gurudwara, sikh temple'),
(204, 25, 'Mosques', 'BUSINESS', 'मस्जिद', 'mosques', 'masjid, mosque'),
(205, 25, 'Religious Organizations', 'BUSINESS', 'धार्मिक संगठन', 'religious-organizations', 'religious trust, samiti'),
(206, 25, 'Temples', 'BUSINESS', 'मंदिर', 'temples', 'mandir, temple'),
(207, 26, 'Moving Shops and Chalant Dukan', 'PROFESSIONAL', 'चलंत दुकान व ठेला वेंडर', 'shop-moving-shops-chalant-dukan', 'chalant dukan, moving shop, cart vendor'),
(208, 26, 'Street Hawkers and Pheriwala', 'PROFESSIONAL', 'फेरीवाला व घुमंतू विक्रेता', 'shop-street-hawkers-pheriwala', 'pheriwala, street hawker, ghumantu dukan, patri dukan'),
(209, 26, 'Agriculture Products', 'BUSINESS', 'कृषि उत्पाद व बीज', 'agriculture-products', 'seeds, fertilizer shop, pesticides'),
(210, 26, 'Automobile Products', 'BUSINESS', 'ऑटोमोबाइल पार्ट्स', 'automobile-products', 'auto parts store, tyre shop, battery'),
(211, 26, 'Books and Stationery', 'BUSINESS', 'किताब व स्टेशनरी', 'books-stationery', 'book store, stationery shop'),
(212, 26, 'Electronics Stores', 'BUSINESS', 'इलेक्ट्रॉनिक्स स्टोर', 'electronics-stores', 'tv fridge store, electronics shop'),
(213, 26, 'Fashion and Garments', 'BUSINESS', 'कपड़ा दुकान व रेडीमेड', 'fashion-garments', 'clothing shop, saree showroom'),
(214, 26, 'Furniture Shops', 'BUSINESS', 'फर्नीचर दुकान', 'furniture-shops', 'furniture store, wooden bed, sofa'),
(215, 26, 'Grocery Shops', 'BUSINESS', 'किराना दुकान', 'grocery-shops', 'grocery, kirana store, ration shop'),
(216, 26, 'Hardware Stores', 'BUSINESS', 'हार्डवेयर दुकान', 'hardware-stores', 'hardware shop, cement dealer, sariya'),
(217, 26, 'Jewellery Shops', 'BUSINESS', 'ज्वैलरी शॉप व आभूषण', 'jewellery-shops', 'jeweller, gold shop, silver ornaments'),
(218, 26, 'Mobile Shops', 'BUSINESS', 'मोबाइल शॉप', 'mobile-shops', 'mobile shop, smartphone store'),
(219, 27, 'Coaches and Fitness Trainers', 'PROFESSIONAL', 'खेल कोच व फिटनेस ट्रेनर', 'coaches-trainers', 'sports coach, gym trainer'),
(220, 27, 'Yoga Teachers', 'PROFESSIONAL', 'योग शिक्षक', 'yoga-teachers', 'yoga teacher, yoga instructor'),
(221, 27, 'Gyms', 'BUSINESS', 'जिम', 'gyms', 'gym, fitness center'),
(222, 27, 'Sports Clubs', 'BUSINESS', 'स्पोर्ट्स क्लब', 'sports-clubs', 'sports club, cricket club'),
(223, 27, 'Sports Shops', 'BUSINESS', 'खेलकूद सामान दुकान', 'sports-shops', 'sports shop, cricket bat'),
(224, 27, 'Stadiums', 'BUSINESS', 'स्टेडियम व मैदान', 'stadiums', 'stadium, rajendra stadium'),
(225, 27, 'Yoga Centres', 'BUSINESS', 'योग केंद्र', 'yoga-centres', 'yoga center, meditation hall'),
(226, 28, 'Computer Technicians', 'PROFESSIONAL', 'कंप्यूटर तकनीशियन', 'computer-technicians', 'computer repair, laptop technician'),
(227, 28, 'Mobile Repair Technicians and Centres', 'PROFESSIONAL', 'मोबाइल रिपेयर सेंटर व मिस्त्री', 'mobile-repair-technicians-centres', 'mobile repair center, mobile repair technician, folder repair, screen replacement'),
(228, 28, 'Software Developers and Coders', 'PROFESSIONAL', 'सॉफ्टवेयर डेवलपर व कोडर', 'software-developers-coders', 'software developer, web developer, coder'),
(229, 28, 'Computer Shops', 'BUSINESS', 'कंप्यूटर दुकान', 'computer-shops', 'computer store, laptop store'),
(230, 28, 'Cyber Cafes', 'BUSINESS', 'साइबर कैफे', 'cyber-cafes', 'cyber cafe, online form center'),
(231, 28, 'IT Companies', 'BUSINESS', 'आईटी कंपनियां', 'it-companies', 'it company, tech agency'),
(232, 28, 'Internet Providers', 'BUSINESS', 'इंटरनेट सेवा प्रदाता', 'internet-providers', 'broadband provider, fiber internet'),
(233, 29, 'Auto Rickshaw Drivers', 'PROFESSIONAL', 'ऑटो रिक्शा चालक', 'auto-rickshaw-drivers', 'auto driver, shared auto, auto rickshaw'),
(234, 29, 'Cycle Rickshaw Drivers', 'PROFESSIONAL', 'साइकिल रिक्शा चालक', 'cycle-rickshaw-drivers', 'cycle rickshaw, manual rickshaw driver, riksha'),
(235, 29, 'Drivers and Cab Operators', 'PROFESSIONAL', 'ड्राइवर व कैब संचालक', 'drivers-cab-operators', 'driver for hire, cab driver, car driver'),
(236, 29, 'E-Rickshaw Drivers', 'PROFESSIONAL', 'ई-रिक्शा चालक व टोटो', 'e-rickshaw-drivers', 'e rickshaw, toto driver, erickshaw driver'),
(237, 29, 'Hand Cart and Thela Operators', 'PROFESSIONAL', 'ठेला चालक व हाथ गाड़ी', 'hand-cart-thela-operators', 'thela, hand cart, non electric thela, cargo handcart'),
(238, 29, 'Airports', 'BUSINESS', 'एयरपोर्ट व हवाई अड्डा पूछताछ', 'airports', 'patna airport, airport cab'),
(239, 29, 'Bus Services', 'BUSINESS', 'बस सेवा व स्टैंड', 'bus-services', 'bus stand chapra, bsrtc bus'),
(240, 29, 'Courier Services', 'BUSINESS', 'कूरियर सेवा', 'courier-services', 'courier, dtdc, blue dart'),
(241, 29, 'Logistics and Freight', 'BUSINESS', 'गुड्स ट्रांसपोर्ट व ट्रक', 'logistics-freight', 'goods transport, truck booking, tempo transport'),
(242, 29, 'Railway Stations', 'BUSINESS', 'रेलवे स्टेशन व पूछताछ', 'railway-stations', 'chapra junction, train enquiry'),
(243, 29, 'Taxi Services', 'BUSINESS', 'टैक्सी सेवा', 'taxi-services', 'taxi booking, outstation cab')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- Seed Initial Verified Listings
INSERT INTO `listings` (`id`, `entity_type`, `category_id`, `subcategory_id`, `block_id`, `title`, `hindi_title`, `slug`, `contact_person`, `mobile`, `whatsapp`, `email`, `website`, `address`, `pincode`, `map_link`, `services`, `description`, `is_verified`, `is_featured`, `status`, `star_rating`) VALUES
(1, 'EMERGENCY', 7, 76, 1, 'Town Police Station (Thana), Chapra', 'नगर थाना, छपरा', 'town-police-station-chapra', 'SHO Chapra Town', '06152-243202', '9431822401', 'sho-chapratown-bih@nic.in', 'https://saran.bihar.gov.in', 'Near Thanachowk, Main Road, Chapra, Saran', '841301', 'https://maps.google.com/?q=Chapra+Town+Police+Station', '24/7 Police Help, Crime Reporting, FIR Filing, Emergency Helpline 112', 'Official Town Police Station providing 24/7 safety and public law enforcement in Chapra Sadar.', 'YES', 'YES', 'ACTIVE', 5.00),

(2, 'HEALTHCARE', 2, 21, 1, 'Saran District Hospital (Sadar Hospital Chapra)', 'सदर अस्पताल, छपरा', 'sadar-hospital-chapra', 'Civil Surgeon Saran', '06152-243405', '9470003200', 'cs-saran-bih@nic.in', 'https://saran.bihar.gov.in', 'Hospital Road, Near Municipal Chowk, Chapra', '841301', 'https://maps.google.com/?q=Sadar+Hospital+Chapra', '24/7 Emergency Care, OPD, ICU, Ambulance, Pathology Lab, Blood Bank', 'The premier government district healthcare facility in Saran, equipping specialized doctors and 24x7 emergency medical services.', 'YES', 'YES', 'ACTIVE', 4.80),

(3, 'PROFESSIONAL', 3, 33, 1, 'District Bar Association, Saran (Chapra Court Advocates Hub)', 'जिला बार एसोसिएशन, सरण (छपरा)', 'district-bar-association-saran', 'President / General Secretary', '06152-242100', '9431426600', 'contact@advocateindex.com', 'https://advocateindex.com/BRSARA', 'District & Sessions Court Premises, Chapra, Saran', '841301', 'https://maps.google.com/?q=Chapra+District+Court', 'Legal Advice, Court Representation, Bail Applications, Legal Documentation, Notary', 'Official District Bar Association Chapra representing legal practitioners in Saran district.', 'YES', 'YES', 'ACTIVE', 4.90),

(4, 'GOVT_OFFICE', 4, 41, 1, 'District Collectorate Office (DM Office Saran)', 'जिलाधिकारी कार्यालय (समाहरणालय छपरा)', 'dm-office-saran-chapra', 'District Magistrate Saran', '06152-245001', '9473191238', 'dm-saran.bih@nic.in', 'https://saran.bihar.gov.in', 'Collectorate Campus, Katchahry Chowk, Chapra, Saran', '841301', 'https://maps.google.com/?q=Collectorate+Office+Chapra', 'Public Grievances, Revenue Administration, Land Records, District Licensing, Government Welfare Schemes', 'Apex administrative headquarters for Saran District located in Chapra city.', 'YES', 'YES', 'ACTIVE', 5.00)
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);

-- Seed Initial People Directory Entries
INSERT INTO `people` (`id`, `full_name`, `hindi_name`, `slug`, `designation`, `profession`, `mobile`, `whatsapp`, `email`, `block_id`, `address`, `pincode`, `bio`, `status`) VALUES
(1, 'Aman Kumar', 'अमन कुमार', 'aman-kumar', 'District Magistrate', 'Government Official', '06152-245001', '9473191238', 'dm-saran.bih@nic.in', 1, 'Collectorate Campus, Chapra', '841301', 'District Magistrate & Collector, Saran (Chapra).', 'ACTIVE'),
(2, 'Dr. Rajiv Ranjan', 'डॉ. राजीव रंजन', 'dr-rajiv-ranjan', 'Senior Surgeon', 'Doctor', '9470003200', '9470003200', 'dr.rajiv@saranindex.com', 1, 'Hospital Road, Chapra', '841301', 'Leading general surgeon at Sadar Hospital Chapra.', 'ACTIVE'),
(3, 'Adv. Vijay Sharma', 'एडवोकेट विजय शर्मा', 'adv-vijay-sharma', 'Senior Advocate', 'Lawyer', '9431426600', '9431426600', 'vijay.legal@gmail.com', 1, 'Civil Court Premises, Chapra', '841301', 'Civil & criminal law advocate with 20+ years practice in Chapra Court.', 'ACTIVE')
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`);

-- 11. Halka & Mauja Table
CREATE TABLE IF NOT EXISTS `halka` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `block` VARCHAR(100) NOT NULL,
    `halka_code` INT NOT NULL,
    `halka_name` VARCHAR(255) DEFAULT NULL,
    `halka_english` VARCHAR(255) DEFAULT NULL,
    `mauja_code` VARCHAR(50) DEFAULT NULL,
    `mauja_name` VARCHAR(255) DEFAULT NULL,
    `mauja_english` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. Saran District Census Table (96 Demographic & Economic Indicator Columns)
CREATE TABLE IF NOT EXISTS `census` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `state_code` VARCHAR(20) DEFAULT NULL,
    `district_code` VARCHAR(20) DEFAULT NULL,
    `cd_block_code` VARCHAR(20) DEFAULT NULL,
    `town_village_code` VARCHAR(20) DEFAULT NULL,
    `ward_code` VARCHAR(20) DEFAULT NULL,
    `eb_code` VARCHAR(20) DEFAULT NULL,
    `state_name` VARCHAR(100) DEFAULT NULL,
    `district_name` VARCHAR(100) DEFAULT NULL,
    `level` VARCHAR(50) DEFAULT NULL,
    `name` VARCHAR(255) DEFAULT NULL,
    `tru_type` VARCHAR(20) DEFAULT NULL,
    `households` INT DEFAULT 0,
    `pop_tot` INT DEFAULT 0,
    `pop_male` INT DEFAULT 0,
    `pop_female` INT DEFAULT 0,
    `p_06` INT DEFAULT 0,
    `m_06` INT DEFAULT 0,
    `f_06` INT DEFAULT 0,
    `sc_tot` INT DEFAULT 0,
    `sc_male` INT DEFAULT 0,
    `sc_female` INT DEFAULT 0,
    `st_tot` INT DEFAULT 0,
    `st_male` INT DEFAULT 0,
    `st_female` INT DEFAULT 0,
    `lit_tot` INT DEFAULT 0,
    `lit_male` INT DEFAULT 0,
    `lit_female` INT DEFAULT 0,
    `ill_tot` INT DEFAULT 0,
    `ill_male` INT DEFAULT 0,
    `ill_female` INT DEFAULT 0,
    `tot_work_tot` INT DEFAULT 0,
    `tot_work_male` INT DEFAULT 0,
    `tot_work_female` INT DEFAULT 0,
    `main_work_tot` INT DEFAULT 0,
    `main_work_male` INT DEFAULT 0,
    `main_work_female` INT DEFAULT 0,
    `main_cl_tot` INT DEFAULT 0,
    `main_cl_male` INT DEFAULT 0,
    `main_cl_female` INT DEFAULT 0,
    `main_al_tot` INT DEFAULT 0,
    `main_al_male` INT DEFAULT 0,
    `main_al_female` INT DEFAULT 0,
    `main_hh_tot` INT DEFAULT 0,
    `main_hh_male` INT DEFAULT 0,
    `main_hh_female` INT DEFAULT 0,
    `main_ot_tot` INT DEFAULT 0,
    `main_ot_male` INT DEFAULT 0,
    `main_ot_female` INT DEFAULT 0,
    `marg_work_tot` INT DEFAULT 0,
    `marg_work_male` INT DEFAULT 0,
    `marg_work_female` INT DEFAULT 0,
    `marg_cl_tot` INT DEFAULT 0,
    `marg_cl_male` INT DEFAULT 0,
    `marg_cl_female` INT DEFAULT 0,
    `marg_al_tot` INT DEFAULT 0,
    `marg_al_male` INT DEFAULT 0,
    `marg_al_female` INT DEFAULT 0,
    `marg_hh_tot` INT DEFAULT 0,
    `marg_hh_male` INT DEFAULT 0,
    `marg_hh_female` INT DEFAULT 0,
    `marg_ot_tot` INT DEFAULT 0,
    `marg_ot_male` INT DEFAULT 0,
    `marg_ot_female` INT DEFAULT 0,
    `marg_work_3_6_tot` INT DEFAULT 0,
    `marg_work_3_6_male` INT DEFAULT 0,
    `marg_work_3_6_female` INT DEFAULT 0,
    `marg_cl_3_6_tot` INT DEFAULT 0,
    `marg_cl_3_6_male` INT DEFAULT 0,
    `marg_cl_3_6_female` INT DEFAULT 0,
    `marg_al_3_6_tot` INT DEFAULT 0,
    `marg_al_3_6_male` INT DEFAULT 0,
    `marg_al_3_6_female` INT DEFAULT 0,
    `marg_hh_3_6_tot` INT DEFAULT 0,
    `marg_hh_3_6_male` INT DEFAULT 0,
    `marg_hh_3_6_female` INT DEFAULT 0,
    `marg_ot_3_6_tot` INT DEFAULT 0,
    `marg_ot_3_6_male` INT DEFAULT 0,
    `marg_ot_3_6_female` INT DEFAULT 0,
    `marg_work_0_3_tot` INT DEFAULT 0,
    `marg_work_0_3_male` INT DEFAULT 0,
    `marg_work_0_3_female` INT DEFAULT 0,
    `marg_cl_0_3_tot` INT DEFAULT 0,
    `marg_cl_0_3_male` INT DEFAULT 0,
    `marg_cl_0_3_female` INT DEFAULT 0,
    `marg_al_0_3_tot` INT DEFAULT 0,
    `marg_al_0_3_male` INT DEFAULT 0,
    `marg_al_0_3_female` INT DEFAULT 0,
    `marg_hh_0_3_tot` INT DEFAULT 0,
    `marg_hh_0_3_male` INT DEFAULT 0,
    `marg_hh_0_3_female` INT DEFAULT 0,
    `marg_ot_0_3_tot` INT DEFAULT 0,
    `marg_ot_0_3_male` INT DEFAULT 0,
    `marg_ot_0_3_female` INT DEFAULT 0,
    `non_work_tot` INT DEFAULT 0,
    `non_work_male` INT DEFAULT 0,
    `non_work_female` INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. LGD Village Master Table
CREATE TABLE IF NOT EXISTS `lgd_village` (
    `id` INT PRIMARY KEY,
    `village_lgd_code` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `name_hindi` VARCHAR(255) DEFAULT NULL,
    `block` VARCHAR(100) NOT NULL,
    `census_2001_code` VARCHAR(50) DEFAULT NULL,
    `census_2011_code` VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- SEED: Politicians & Public Representatives Category (#30)
-- Added: 2026-08-07 | Does not modify existing IDs
-- ============================================================

INSERT INTO `categories` (`id`, `name`, `hindi_name`, `icon`, `slug`, `section`, `status`)
VALUES (30, 'Politics', 'राजनीति', 'bi-person-badge-fill', 'politics', 'GOVT', 'ACTIVE')
ON DUPLICATE KEY UPDATE
    `name`       = VALUES(`name`),
    `hindi_name` = VALUES(`hindi_name`),
    `icon`       = VALUES(`icon`),
    `slug`       = VALUES(`slug`);

INSERT INTO `subcategories` (`id`, `category_id`, `name`, `hindi_name`, `slug`, `type`) VALUES
(244, 30, 'Ward Member',              'वार्ड सदस्य',             'ward-member',              'PROFESSIONAL'),
(245, 30, 'Panch',                    'पंच',                      'panch',                    'PROFESSIONAL'),
(246, 30, 'Mukhiya',                  'मुखिया',                   'mukhiya',                  'PROFESSIONAL'),
(247, 30, 'Sarpanch',                 'सरपंच',                    'sarpanch',                 'PROFESSIONAL'),
(248, 30, 'Panchayat Samiti Member',  'पंचायत समिति सदस्य',      'panchayat-samiti-member',  'PROFESSIONAL'),
(249, 30, 'Jila Parishad Member',     'जिला परिषद सदस्य',        'jila-parishad-member',     'PROFESSIONAL'),
(250, 30, 'Nagar Panchayat Ward',     'नगर पंचायत वार्ड',         'nagar-panchayat-ward',     'PROFESSIONAL'),
(251, 30, 'Nagar Parishad Ward',      'नगर परिषद वार्ड',           'nagar-parishad-ward',      'PROFESSIONAL'),
(252, 30, 'MLA',                      'विधायक',                    'mla',                      'PROFESSIONAL'),
(253, 30, 'MLC',                      'विधान पार्षद',              'mlc',                      'PROFESSIONAL'),
(254, 30, 'MP (Lok Sabha)',           'सांसद (लोक सभा)',           'mp-lok-sabha',             'PROFESSIONAL'),
(255, 30, 'MP (Rajya Sabha)',         'सांसद (राज्य सभा)',         'mp-rajya-sabha',           'PROFESSIONAL'),
(256, 30, 'Minister (State)',         'मंत्री (राज्य)',             'minister-state',           'PROFESSIONAL'),
(257, 30, 'Minister (Central)',       'मंत्री (केंद्र)',             'minister-central',         'PROFESSIONAL'),
(258, 30, 'Ex-Politician',            'पूर्व नेता',                 'ex-politician',            'PROFESSIONAL'),
(259, 30, 'Political Party Office',   'राजनीतिक दल कार्यालय',     'political-party-office',   'BUSINESS')
ON DUPLICATE KEY UPDATE
    `category_id` = VALUES(`category_id`),
    `name`        = VALUES(`name`),
    `hindi_name`  = VALUES(`hindi_name`),
    `slug`        = VALUES(`slug`),
    `type`        = VALUES(`type`);

-- Additional subcategories for Politicians (#260-#266) | Added: 2026-08-07
INSERT INTO `subcategories` (`id`, `category_id`, `name`, `hindi_name`, `slug`, `type`) VALUES
(260, 30, 'Nagar Nigam Ward',          'नगर निगम वार्ड',         'nagar-nigam-ward',          'PROFESSIONAL'),
(261, 30, 'Chairman',                  'अध्यक्ष',                  'chairman',                  'PROFESSIONAL'),
(262, 30, 'Vice Chairman',             'उपाध्यक्ष',                'vice-chairman',             'PROFESSIONAL'),
(263, 30, 'Jila Parishad Adhyaksh',   'जिला परिषद अध्यक्ष',      'jila-parishad-adhyaksh',    'PROFESSIONAL'),
(264, 30, 'Jila Parishad Upadhyaksh', 'जिला परिषद उपाध्यक्ष',    'jila-parishad-upadhyaksh',  'PROFESSIONAL'),
(265, 30, 'Pramukh',                  'प्रमुख',                   'pramukh',                   'PROFESSIONAL'),
(266, 30, 'Up Pramukh',               'उप प्रमुख',                'up-pramukh',                'PROFESSIONAL')
ON DUPLICATE KEY UPDATE
    `category_id` = VALUES(`category_id`),
    `name`        = VALUES(`name`),
    `hindi_name`  = VALUES(`hindi_name`),
    `slug`        = VALUES(`slug`),
    `type`        = VALUES(`type`);
